export type ICastListArray = { id: string; caste: string };
export const CastListArray = [
  { id: "581", caste: "Hindu: 24 Manai Telugu Chettiar" },
  { id: "613", caste: "Hindu: 96K Kokanastha" },
  { id: "278", caste: "Hindu: Ad Dharmi" },
  { id: "407", caste: "Hindu: Adi Andhra" },
  { id: "16", caste: "Hindu: Adi Dravida" },
  { id: "408", caste: "Hindu: Adi Karnataka" },
  { id: "409", caste: "Hindu: Agamudayar" },
  { id: "17", caste: "Hindu: Aggarwal" },
  { id: "168", caste: "Hindu: Agri" },
  { id: "410", caste: "Hindu: Ahir" },
  { id: "279", caste: "Hindu: Ahom" },
  { id: "182", caste: "Hindu: Ambalavasi" },
  { id: "582", caste: "Hindu: Amma Kodava" },
  { id: "583", caste: "Hindu: Arakh Arakvanshiya" },
  { id: "584", caste: "Hindu: Arekatica" },
  { id: "18", caste: "Hindu: Arora" },
  { id: "183", caste: "Hindu: Arunthathiyar" },
  { id: "19", caste: "Hindu: Arya Vysya" },
  { id: "585", caste: "Hindu: Ayyaraka" },
  { id: "586", caste: "Hindu: Badaga" },
  { id: "559", caste: "Hindu: Badhai" },
  { id: "587", caste: "Hindu: Bagdi" },
  { id: "227", caste: "Hindu: Baghel Gaderiya" },
  { id: "614", caste: "Hindu: Bahi" },
  { id: "252", caste: "Hindu: Baidya" },
  { id: "281", caste: "Hindu: Baishnab" },
  { id: "282", caste: "Hindu: Baishya" },
  { id: "648", caste: "Hindu: Baishya Kapali" },
  { id: "588", caste: "Hindu: Bajantri" },
  { id: "283", caste: "Hindu: Balija" },
  { id: "21", caste: "Hindu: Balija Naidu" },
  { id: "576", caste: "Hindu: Banayat Oriya" },
  { id: "499", caste: "Hindu: Bania" },
  { id: "284", caste: "Hindu: Banik" },
  { id: "411", caste: "Hindu: Banjara" },
  { id: "589", caste: "Hindu: Barai" },
  { id: "229", caste: "Hindu: Bari" },
  { id: "590", caste: "Hindu: Baria" },
  { id: "285", caste: "Hindu: Hindu: Barujibi" },
  { id: "569", caste: "Hindu: Beldar" },
  { id: "286", caste: "Hindu: Besta" },
  { id: "574", caste: "Hindu: Bhajantri" },
  { id: "22", caste: "Hindu: Bhandari" },
  { id: "231", caste: "Hindu: Bhatia" },
  { id: "412", caste: "Hindu: Bhatraju" },
  { id: "287", caste: "Hindu: Bhavsar" },
  { id: "288", caste: "Hindu: Bhovi / Bhoi" },
  { id: "637", caste: "Hindu: Bhoyar" },
  { id: "591", caste: "Hindu: Bhulia / Meher" },
  { id: "24", caste: "Hindu: Billava" },
  { id: "512", caste: "Hindu: Bisa Agarwal" },
  { id: "413", caste: "Hindu: Bishnoi / Vishnoi" },
  { id: "592", caste: "Hindu: Bondili" },
  { id: "184", caste: "Hindu: Boyer" },
  { id: "593", caste: "Hindu: Brahmakshatriya" },
  { id: "289", caste: "Hindu: Brahmbatt" },
  { id: "500", caste: "Hindu: Brahmin" },
  { id: "26", caste: "Hindu: Brahmin 6000 Niyogi" },
  { id: "27", caste: "Hindu: Brahmin Anavil" },
  { id: "478", caste: "Hindu: Brahmin Andhra" },
  { id: "234", caste: "Hindu: Brahmin Audichya" },
  { id: "414", caste: "Hindu: Brahmin Bajkhedwal" },
  { id: "513", caste: "Hindu: Brahmin Bardai" },
  { id: "290", caste: "Hindu: Brahmin Barendra" },
  { id: "482", caste: "Hindu: Brahmin Bengali" },
  { id: "415", caste: "Hindu: Brahmin Bhargava" },
  { id: "291", caste: "Hindu: Brahmin Bhatt" },
  { id: "28", caste: "Hindu: Brahmin Bhumihar" },
  { id: "416", caste: "Hindu: Brahmin Brahacharanam" },
  { id: "514", caste: "Hindu: Brahmin BrahmBhatt" },
  { id: "515", caste: "Hindu: Brahmin Brajastha Maithil" },
  { id: "566", caste: "Hindu: Brahmin Chittpavan Kokanastha" },
  { id: "516", caste: "Hindu: Brahmin Dadhich" },
  { id: "29", caste: "Hindu: Brahmin Daivadnya" },
  { id: "594", caste: "Hindu: Brahmin Danua" },
  { id: "30", caste: "Hindu: Brahmin Deshastha" },
  { id: "545", caste: "Hindu: Brahmin Devrukhe" },
  { id: "292", caste: "Hindu: Brahmin Dhiman" },
  { id: "293", caste: "Hindu: Brahmin Dravida" },
  { id: "294", caste: "Hindu: Brahmin Dunua" },
  { id: "518", caste: "Hindu: Brahmin Embrandiri" },
  { id: "31", caste: "Hindu: Brahmin Garhwali" },
  { id: "32", caste: "Hindu: Brahmin Gaud Saraswat (GSB)" },
  { id: "33", caste: "Hindu: Brahmin Gaur" },
  { id: "34", caste: "Hindu: Brahmin Goswami" },
  { id: "417", caste: "Hindu: Brahmin Gujar Gaur" },
  { id: "480", caste: "Hindu: Brahmin Gujrati" },
  { id: "418", caste: "Hindu: Brahmin Gurukkal" },
  { id: "295", caste: "Hindu: Brahmin Halua" },
  { id: "35", caste: "Hindu: Brahmin Havyaka" },
  { id: "296", caste: "Hindu: Brahmin Hoysala" },
  { id: "65", caste: "Hindu: Brahmin Iyengar" },
  { id: "66", caste: "Hindu: Brahmin Iyer" },
  { id: "420", caste: "Hindu: Brahmin Jangid" },
  { id: "421", caste: "Hindu: Brahmin Jangra" },
  { id: "299", caste: "Hindu: Brahmin Jhadua" },
  { id: "262", caste: "Hindu: Brahmin Jhijhotiya" },
  { id: "422", caste: "Hindu: Brahmin Jogi" },
  { id: "519", caste: "Hindu: Brahmin Jyotish" },
  { id: "495", caste: "Hindu: Brahmin Kannada" },
  { id: "473", caste: "Hindu: Brahmin Kanyakubj" },
  { id: "36", caste: "Hindu: Brahmin Kanyakubj" },
  { id: "37", caste: "Hindu: Brahmin Karhade" },
  { id: "38", caste: "Hindu: Brahmin Kashmiri Pandit" },
  { id: "520", caste: "Hindu: Brahmin Khadayat" },
  { id: "521", caste: "Hindu: Brahmin Khandelwal" },
  { id: "522", caste: "Hindu: Brahmin Khedaval" },
  { id: "39", caste: "Hindu: Brahmin Koknastha" },
  { id: "300", caste: "Hindu: Brahmin Kota" },
  { id: "301", caste: "Hindu: Brahmin Kulin" },
  { id: "40", caste: "Hindu: Brahmin Kumaoni" },
  { id: "41", caste: "Hindu: Brahmin Madhwa" },
  { id: "481", caste: "Hindu: Brahmin Maharastra" },
  { id: "42", caste: "Hindu: Brahmin Maithil" },
  { id: "523", caste: "Hindu: Brahmin Malviya" },
  { id: "547", caste: "Hindu: Brahmin Marwari" },
  { id: "524", caste: "Hindu: Brahmin Mevada" },
  { id: "302", caste: "Hindu: Brahmin Modh" },
  { id: "303", caste: "Hindu: Brahmin Mohyal" },
  { id: "43", caste: "Hindu: Brahmin Nagar" },
  { id: "304", caste: "Hindu: Brahmin Namboodiri" },
  { id: "44", caste: "Hindu: Brahmin Narmadiya" },
  { id: "641", caste: "Hindu: Brahmin Nayi / Nai" },
  { id: "525", caste: "Hindu: Brahmin Paliwal" },
  { id: "306", caste: "Hindu: Brahmin Panda" },
  { id: "307", caste: "Hindu: Brahmin Pandit" },
  { id: "526", caste: "Hindu: Brahmin Panicker" },
  { id: "261", caste: "Hindu: Brahmin Pareek" },
  { id: "237", caste: "Hindu: Brahmin Pushkarna" },
  { id: "483", caste: "Hindu: Brahmin Rajasthani" },
  { id: "527", caste: "Hindu: Brahmin Rajgor" },
  { id: "309", caste: "Hindu: Brahmin Rarhi" },
  { id: "45", caste: "Hindu: Brahmin Rigvedi" },
  { id: "310", caste: "Hindu: Brahmin Rudraj" },
  { id: "633", caste: "Hindu: Brahmin Sachora" },
  { id: "311", caste: "Hindu: Brahmin Sakaldwipi" },
  { id: "180", caste: "Hindu: Brahmin Sanadya" },
  { id: "634", caste: "Hindu: Brahmin Sanchihar" },
  { id: "312", caste: "Hindu: Brahmin Sanketi" },
  { id: "46", caste: "Hindu: Brahmin Saraswat" },
  { id: "546", caste: "Hindu: Brahmin Sarotri" },
  { id: "528", caste: "Hindu: Brahmin Sarua" },
  { id: "47", caste: "Hindu: Brahmin Saryuparin" },
  { id: "251", caste: "Hindu: Brahmin Shivalli" },
  { id: "314", caste: "Hindu: Brahmin Shrimali" },
  { id: "529", caste: "Hindu: Brahmin Sikhwal" },
  { id: "48", caste: "Hindu: Brahmin Smartha" },
  { id: "315", caste: "Hindu: Brahmin Sri Vishnava" },
  { id: "530", caste: "Hindu: Brahmin Stanika" },
  { id: "531", caste: "Hindu: Brahmin Tapodhan" },
  { id: "179", caste: "Hindu: Brahmin Tyagi" },
  { id: "476", caste: "Hindu: Brahmin Utkal" },
  { id: "49", caste: "Hindu: Brahmin Vaidiki" },
  { id: "595", caste: "Hindu: Brahmin Vaikhanasa" },
  { id: "532", caste: "Hindu: Brahmin Vaikhawas" },
  { id: "544", caste: "Hindu: Brahmin Vaishnav" },
  { id: "533", caste: "Hindu: Brahmin Valam" },
  { id: "534", caste: "Hindu: Brahmin Velanadu" },
  { id: "402", caste: "Hindu: Brahmin Viswa" },
  { id: "316", caste: "Hindu: Brahmin Vyas" },
  { id: "423", caste: "Hindu: Brahmin Yajurvedi" },
  { id: "535", caste: "Hindu: Brahmin Zalora" },
  { id: "317", caste: "Hindu: Brahmo" },
  { id: "615", caste: "Hindu: Buddar" },
  { id: "210", caste: "Hindu: Bunt Shetty" },
  { id: "616", caste: "Hindu: Chalawadi / Holeya" },
  { id: "318", caste: "Hindu: Chamar" },
  { id: "52", caste: "Hindu: Chambhar" },
  { id: "319", caste: "Hindu: Chandravanshi Kahar" },
  { id: "596", caste: "Hindu: Charan" },
  { id: "320", caste: "Hindu: Chasa" },
  { id: "424", caste: "Hindu: Chattada Sri Vaishnava" },
  { id: "321", caste: "Hindu: Chaudary" },
  { id: "53", caste: "Hindu: Chaurasia" },
  { id: "597", caste: "Hindu: Chennadasar" },
  { id: "617", caste: "Hindu: Cheramar" },
  { id: "54", caste: "Hindu: Chettiar" },
  { id: "322", caste: "Hindu: Chhetri" },
  { id: "618", caste: "Hindu: Chippolu Mera" },
  { id: "55", caste: "Hindu: CKP" },
  { id: "56", caste: "Hindu: Coorgi" },
  { id: "598", caste: "Hindu: Dasapalanjika Kannada Saineegar" },
  { id: "425", caste: "Hindu: Deshastha Maratha" },
  { id: "230", caste: "Hindu: Devadigas" },
  { id: "324", caste: "Hindu: Devang Koshthi" },
  { id: "57", caste: "Hindu: Devanga" },
  { id: "323", caste: "Hindu: Devendra Kula Vellalar" },
  { id: "635", caste: "Hindu: Devipujak (Vaghri)" },
  { id: "58", caste: "Hindu: Dhangar" },
  { id: "646", caste: "Hindu: Dhanuk" },
  { id: "171", caste: "Hindu: Dheevara" },
  { id: "651", caste: "Hindu: Dhiman" },
  { id: "326", caste: "Hindu: Dhoba" },
  { id: "166", caste: "Hindu: Dhobi" },
  { id: "558", caste: "Hindu: Dhor / Dhoar" },
  { id: "599", caste: "Hindu: Dommala" },
  { id: "600", caste: "Hindu: Dumal" },
  { id: "426", caste: "Hindu: Dusadh" },
  { id: "178", caste: "Hindu: Edigas" },
  { id: "59", caste: "Hindu: Ezhava" },
  { id: "185", caste: "Hindu: Ezhuthachan" },
  { id: "327", caste: "Hindu: Gabit" },
  { id: "560", caste: "Hindu: Gangai / Ganesh" },
  { id: "187", caste: "Hindu: Ganiga" },
  { id: "328", caste: "Hindu: Garhwali" },
  { id: "601", caste: "Hindu: Gatti" },
  { id: "247", caste: "Hindu: Gavali" },
  { id: "602", caste: "Hindu: Gavandi" },
  { id: "188", caste: "Hindu: Gavara" },
  { id: "603", caste: "Hindu: Ghisadi" },
  { id: "329", caste: "Hindu: Ghumar" },
  { id: "330", caste: "Hindu: Goala" },
  { id: "331", caste: "Hindu: Goan" },
  { id: "427", caste: "Hindu: Gomantak Maratha" },
  { id: "548", caste: "Hindu: Gond Gondi Raj Gond" },
  { id: "428", caste: "Hindu: Gondhali" },
  { id: "568", caste: "Hindu: Gopal" },
  { id: "60", caste: "Hindu: Goud" },
  { id: "61", caste: "Hindu: Gounder" },
  { id: "62", caste: "Hindu: Gowda" },
  { id: "429", caste: "Hindu: Gramani" },
  { id: "332", caste: "Hindu: Gudia" },
  { id: "63", caste: "Hindu: Gujjar" },
  { id: "64", caste: "Hindu: Gupta" },
  { id: "652", caste: "Hindu: Guptan" },
  { id: "430", caste: "Hindu: Gurav" },
  { id: "561", caste: "Hindu: Halba Koshti" },
  { id: "223", caste: "Hindu: Hegde" },
  { id: "604", caste: "Hindu: Helava" },
  { id: "605", caste: "Hindu: Jaalari" },
  { id: "70", caste: "Hindu: Jaiswal" },
  { id: "606", caste: "Hindu: Jandra" },
  { id: "333", caste: "Hindu: Jangam" },
  { id: "71", caste: "Hindu: Jat" },
  { id: "72", caste: "Hindu: Jatav" },
  { id: "653", caste: "Hindu: Jetty Malla" },
  { id: "657", caste: "Hindu: Jingar" },
  { id: "607", caste: "Hindu: Kachara" },
  { id: "334", caste: "Hindu: Kadava patel" },
  { id: "432", caste: "Hindu: Kahar" },
  { id: "335", caste: "Hindu: Kaibarta" },
  { id: "608", caste: "Hindu: Kaikaala" },
  { id: "619", caste: "Hindu: Kakkalan" },
  { id: "433", caste: "Hindu: Kalal" },
  { id: "554", caste: "Hindu: Kalanji" },
  { id: "74", caste: "Hindu: Kalar" },
  { id: "654", caste: "Hindu: Kalinga" },
  { id: "434", caste: "Hindu: Kalinga Vysya" },
  { id: "609", caste: "Hindu: Kalita" },
  { id: "337", caste: "Hindu: Kalwar" },
  { id: "225", caste: "Hindu: Kamboj" },
  { id: "73", caste: "Hindu: Kamma" },
  { id: "610", caste: "Hindu: Kanakkan Padanna" },
  { id: "620", caste: "Hindu: Kaniyan" },
  { id: "338", caste: "Hindu: Kansari" },
  { id: "611", caste: "Hindu: Kansyakaar" },
  { id: "435", caste: "Hindu: Kapol" },
  { id: "501", caste: "Hindu: Kapu" },
  { id: "218", caste: "Hindu: Kapu Munnuru" },
  { id: "612", caste: "Hindu: Karakala Bhakthula" },
  { id: "339", caste: "Hindu: Karana" },
  { id: "340", caste: "Hindu: Karmakar" },
  { id: "190", caste: "Hindu: Karuneegar" },
  { id: "341", caste: "Hindu: Kasar" },
  { id: "342", caste: "Hindu: Kashyap" },
  { id: "567", caste: "Hindu: Katiya" },
  { id: "502", caste: "Hindu: Kayastha" },
  { id: "77", caste: "Hindu: Khandayat" },
  { id: "343", caste: "Hindu: Khandelwal" },
  { id: "551", caste: "Hindu: Kharvi" },
  { id: "405", caste: "Hindu: Kharwar" },
  { id: "226", caste: "Hindu: Khatik" },
  { id: "484", caste: "Hindu: Khatri" },
  { id: "562", caste: "Hindu: Koeri / Koiri" },
  { id: "436", caste: "Hindu: Kokanastha Maratha" },
  { id: "79", caste: "Hindu: Koli" },
  { id: "437", caste: "Hindu: Koli Mahadev" },
  { id: "80", caste: "Hindu: Kongu Vellala Gounder" },
  { id: "344", caste: "Hindu: Konkani" },
  { id: "564", caste: "Hindu: Koracha" },
  { id: "621", caste: "Hindu: Korama" },
  { id: "345", caste: "Hindu: Kori" },
  { id: "645", caste: "Hindu: Korvi" },
  { id: "81", caste: "Hindu: Koshti" },
  { id: "622", caste: "Hindu: Krishnavaka" },
  { id: "503", caste: "Hindu: Kshatriya" },
  { id: "217", caste: "Hindu: Kshatriya Agnikula" },
  { id: "346", caste: "Hindu: Kudumbi" },
  { id: "191", caste: "Hindu: Kulalar" },
  { id: "347", caste: "Hindu: Kulita" },
  { id: "83", caste: "Hindu: Kumawat" },
  { id: "438", caste: "Hindu: Kumbhakar" },
  { id: "228", caste: "Kumhar / Kumbhar" },
  { id: "192", caste: "Hindu: Kummari" },
  { id: "84", caste: "Hindu: Kunbi" },
  { id: "85", caste: "Hindu: Kurmi" },
  { id: "349", caste: "Hindu: Kurmi Kshatriya" },
  { id: "86", caste: "Hindu: Kuruba" },
  { id: "350", caste: "Hindu: Kuruhina Shetty" },
  { id: "193", caste: "Hindu: Kurumbar" },
  { id: "87", caste: "Hindu: Kushwaha" },
  { id: "351", caste: "Hindu: Kutchi" },
  { id: "439", caste: "Hindu: Kutchi Gurjar" },
  { id: "352", caste: "Hindu: Lambadi" },
  { id: "649", caste: "Hindu: Laxminarayan gola" },
  { id: "88", caste: "Hindu: Leva Patidar" },
  { id: "354", caste: "Hindu: Leva Patil" },
  { id: "89", caste: "Hindu: Lingayat" },
  { id: "440", caste: "Hindu: Lodhi Rajput" },
  { id: "90", caste: "Hindu: Lohana" },
  { id: "250", caste: "Hindu: Lohar" },
  { id: "355", caste: "Hindu: Lubana" },
  { id: "194", caste: "Hindu: Madiga" },
  { id: "356", caste: "Hindu: Mahajan" },
  { id: "357", caste: "Hindu: Mahar" },
  { id: "623", caste: "Hindu: Mahendra" },
  { id: "91", caste: "Hindu: Maheshwari" },
  { id: "358", caste: "Hindu: Mahindra" },
  { id: "92", caste: "Hindu: Mahisya" },
  { id: "359", caste: "Hindu: Majabi Mazhbi" },
  { id: "195", caste: "Hindu: Mala" },
  { id: "93", caste: "Hindu: Mali" },
  { id: "164", caste: "Hindu: Mallah" },
  { id: "573", caste: "Hindu: Manikpuri" },
  { id: "360", caste: "Hindu: Manipuri" },
  { id: "557", caste: "Hindu: Manjhi" },
  { id: "361", caste: "Hindu: Mapila" },
  { id: "94", caste: "Hindu: Maratha" },
  { id: "441", caste: "Hindu: Maravar" },
  { id: "197", caste: "Hindu: Maruthuvar" },
  { id: "95", caste: "Hindu: Marwari" },
  { id: "362", caste: "Hindu: Matang" },
  { id: "442", caste: "Hindu: Mathur" },
  { id: "96", caste: "Hindu: Maurya" },
  { id: "364", caste: "Hindu: Meena" },
  { id: "198", caste: "Hindu: Meenavar" },
  { id: "365", caste: "Hindu: Mehra" },
  { id: "97", caste: "Hindu: Menon" },
  { id: "170", caste: "Hindu: Meru" },
  { id: "366", caste: "Hindu: Meru darji" },
  { id: "367", caste: "Hindu: Modak" },
  { id: "100", caste: "Hindu: Mogaveera" },
  { id: "235", caste: "Hindu: Monchi" },
  { id: "443", caste: "Hindu: Motati Reddy" },
  { id: "504", caste: "Hindu: Mudaliar" },
  { id: "99", caste: "Hindu: Mudaliar Arcot" },
  { id: "199", caste: "Hindu: Mudiraj" },
  { id: "201", caste: "Hindu: Muthuraja" },
  { id: "625", caste: "Hindu: Naagavamsam" },
  { id: "101", caste: "Hindu: Nadar" },
  { id: "626", caste: "Hindu: Nagaralu" },
  { id: "202", caste: "Hindu: Naicker" },
  { id: "102", caste: "Hindu: Naidu" },
  { id: "233", caste: "Hindu: Naik Nayak Nayaka" },
  { id: "505", caste: "Hindu: Nair" },
  { id: "400", caste: "Hindu: Nair Veluthedathu" },
  { id: "401", caste: "Hindu: Nair Vilakkithala" },
  { id: "253", caste: "Hindu: Namasudra / Namosudra" },
  { id: "104", caste: "Hindu: Nambiar" },
  { id: "655", caste: "Hindu: Nambisan" },
  { id: "105", caste: "Hindu: Namboodiri" },
  { id: "572", caste: "Hindu: Namdev Chhipa" },
  { id: "638", caste: "Hindu: Nandiwale" },
  { id: "369", caste: "Hindu: Napit" },
  { id: "553", caste: "Hindu: Nath Jogi" },
  { id: "107", caste: "Hindu: Nayee (Barber)" },
  { id: "106", caste: "Hindu: Nepali" },
  { id: "647", caste: "Hindu: Nessi / Kurni" },
  { id: "370", caste: "Hindu: Nhavi" },
  { id: "555", caste: "Hindu: Nonia" },
  { id: "470", caste: "Hindu: OBC" },
  { id: "643", caste: "Hindu: Odan" },
  { id: "371", caste: "Hindu: Oswal" },
  { id: "627", caste: "Hindu: Otari" },
  { id: "108", caste: "Hindu: Padmashali" },
  { id: "372", caste: "Hindu: Pal" },
  { id: "373", caste: "Hindu: Panchal" },
  { id: "444", caste: "Hindu: Panchamsali" },
  { id: "445", caste: "Hindu: Pandaram" },
  { id: "204", caste: "Hindu: Panicker" },
  { id: "205", caste: "Hindu: Parkava Kulam" },
  { id: "640", caste: "Hindu: Parvatha Rajakulam" },
  { id: "374", caste: "Hindu: Pasi" },
  { id: "506", caste: "Hindu: Patel" },
  { id: "176", caste: "Hindu: patel Dodia" },
  { id: "110", caste: "Hindu: patel Kadva" },
  { id: "111", caste: "Hindu: patel Leva" },
  { id: "543", caste: "Hindu: Patel Lodhi" },
  { id: "571", caste: "Hindu: Pathare Prabhu" },
  { id: "507", caste: "Hindu: Patil" },
  { id: "206", caste: "Hindu: Patnaick" },
  { id: "375", caste: "Hindu: Patra" },
  { id: "446", caste: "Hindu: Perika" },
  { id: "114", caste: "Hindu: Pillai" },
  { id: "628", caste: "Hindu: Poosala" },
  { id: "115", caste: "Hindu: Prajapati" },
  { id: "578", caste: "Hindu: Rabari" },
  { id: "447", caste: "Hindu: Raigar" },
  { id: "556", caste: "Hindu: Raikwar" },
  { id: "207", caste: "Hindu: Rajaka" },
  { id: "448", caste: "Hindu: Rajbhar" },
  { id: "376", caste: "Hindu: Rajbongshi" },
  { id: "550", caste: "Hindu: Rajpurohit" },
  { id: "508", caste: "Hindu: Rajput" },
  { id: "117", caste: "Hindu: Rajput Garhwali" },
  { id: "118", caste: "Hindu: Rajput Kumaoni" },
  { id: "449", caste: "Hindu: Rajput Negi" },
  { id: "221", caste: "Hindu: Rajput Rohella Tank" },
  { id: "377", caste: "Hindu: Ramdasia" },
  { id: "378", caste: "Hindu: Ramgarhia" },
  { id: "549", caste: "Hindu: Ramoshi Berad Bedar" },
  { id: "379", caste: "Hindu: Ravidasia" },
  { id: "380", caste: "Hindu: Rawat" },
  { id: "119", caste: "Hindu: Reddy" },
  { id: "639", caste: "Hindu: Ror" },
  { id: "120", caste: "Hindu: Sadgope" },
  { id: "381", caste: "Hindu: Saha" },
  { id: "382", caste: "Hindu: Sahu" },
  { id: "177", caste: "Hindu: Saini" },
  { id: "208", caste: "Hindu: Saliya" },
  { id: "570", caste: "Hindu: Sathwara" },
  { id: "656", caste: "Hindu: Savji" },
  { id: "565", caste: "Hindu: Sawantwadi" },
  { id: "121", caste: "Hindu: Scheduled Caste" },
  { id: "403", caste: "Hindu: Scheduled Tribe" },
  { id: "209", caste: "Hindu: Senai Thalaivar" },
  { id: "450", caste: "Hindu: Senguntha Mudaliyar" },
  { id: "383", caste: "Hindu: Settibalija" },
  { id: "165", caste: "Hindu: Shah" },
  { id: "122", caste: "Hindu: Shimpi" },
  { id: "123", caste: "Hindu: Sindhi" },
  { id: "451", caste: "Hindu: Sindhi Amil" },
  { id: "452", caste: "Hindu: Sindhi Baibhand" },
  { id: "511", caste: "Hindu: Sindhi Bhanusali" },
  { id: "453", caste: "Hindu: Sindhi Bhatia" },
  { id: "536", caste: "Hindu: Sindhi Chhapru" },
  { id: "542", caste: "Hindu: Sindhi Daru" },
  { id: "537", caste: "Hindu: Sindhi Hydrabadi" },
  { id: "454", caste: "Hindu: Sindhi Larai" },
  { id: "538", caste: "Hindu: Sindhi Larkan" },
  { id: "455", caste: "Hindu: Sindhi Larkana" },
  { id: "539", caste: "Hindu: Sindhi Lohana" },
  { id: "456", caste: "Hindu: Sindhi Rohiri" },
  { id: "457", caste: "Hindu: Sindhi Sahiti" },
  { id: "458", caste: "Hindu: Sindhi Sakkhar" },
  { id: "540", caste: "Hindu: Sindhi Sehwani" },
  { id: "459", caste: "Hindu: Sindhi Shikarpuri" },
  { id: "541", caste: "Hindu: Sindhi Thatai" },
  { id: "460", caste: "Hindu: SKP" },
  { id: "124", caste: "Hindu: Somvanshi" },
  { id: "241", caste: "Hindu: Somvanshi Kayastha Prabhu" },
  { id: "125", caste: "Hindu: Sonar / Sunar" },
  { id: "384", caste: "Hindu: Soni" },
  { id: "461", caste: "Hindu: Sood" },
  { id: "211", caste: "Hindu: Sourashtra" },
  { id: "126", caste: "Hindu: Sozhiya Vellalar" },
  { id: "232", caste: "Hindu: Srisayani" },
  { id: "239", caste: "Hindu: SSK" },
  { id: "385", caste: "Hindu: Subarna Banik" },
  { id: "386", caste: "Hindu: Sudi Suri Sundhi Shaundik" },
  { id: "127", caste: "Hindu: Sutar" },
  { id: "387", caste: "Hindu: Swakula sali" },
  { id: "128", caste: "Hindu: Swarnkar" },
  { id: "388", caste: "Hindu: Tamboli" },
  { id: "650", caste: "Hindu: Tammali" },
  { id: "389", caste: "Hindu: Tanti" },
  { id: "163", caste: "Hindu: Tantuway" },
  { id: "212", caste: "Hindu: Telaga" },
  { id: "129", caste: "Hindu: Teli" },
  { id: "390", caste: "Hindu: Thakkar" },
  { id: "391", caste: "Hindu: Thakur" },
  { id: "642", caste: "Hindu: Tharakan" },
  { id: "130", caste: "Hindu: Thevar Mukkulathor" },
  { id: "392", caste: "Hindu: Thigala" },
  { id: "131", caste: "Hindu: Thiyya" },
  { id: "462", caste: "Hindu: Tili" },
  { id: "463", caste: "Hindu: Togata" },
  { id: "464", caste: "Hindu: Tonk Kshatriya" },
  { id: "393", caste: "Hindu: Tribe" },
  { id: "465", caste: "Hindu: Turupu Kapu" },
  { id: "394", caste: "Hindu: Uppara" },
  { id: "577", caste: "Hindu: Vadar" },
  { id: "395", caste: "Hindu: Vaddera" },
  { id: "466", caste: "Hindu: Vaidiki Velanadu" },
  { id: "133", caste: "Hindu: Vaish" },
  { id: "509", caste: "Hindu: Vaishnav" },
  { id: "135", caste: "Hindu: Vaishnav Vanik" },
  { id: "396", caste: "Hindu: Vaishnava" },
  { id: "136", caste: "Hindu: Vaishya" },
  { id: "397", caste: "Hindu: Vaishya Vani" },
  { id: "629", caste: "Hindu: Vallala" },
  { id: "467", caste: "Hindu: Valluvar" },
  { id: "137", caste: "Hindu: Valmiki" },
  { id: "398", caste: "Hindu: Vania" },
  { id: "399", caste: "Hindu: Vaniya" },
  { id: "630", caste: "Hindu: Vanjara" },
  { id: "224", caste: "Hindu: Vanjari" },
  { id: "236", caste: "Hindu: Vankar" },
  { id: "213", caste: "Hindu: Vannar" },
  { id: "214", caste: "Hindu: Vannia Kula Kshatriyar" },
  { id: "138", caste: "Hindu: Vanniyar" },
  { id: "624", caste: "Hindu: Variar" },
  { id: "139", caste: "Hindu: Varshney" },
  { id: "215", caste: "Hindu: Veershaiva Veera Saivam" },
  { id: "631", caste: "Hindu: Velaan" },
  { id: "142", caste: "Hindu: Velama" },
  { id: "468", caste: "Hindu: Velan" },
  { id: "510", caste: "Hindu: Vellalar" },
  { id: "469", caste: "Hindu: Vettuva Gounder" },
  { id: "143", caste: "Hindu: Vishwakarma" },
  { id: "144", caste: "Hindu: Vokkaliga" },
  { id: "145", caste: "Hindu: Vysya" },
  { id: "575", caste: "Hindu: Wani" },
  { id: "146", caste: "Hindu: Yadav / Yadava" },
  { id: "632", caste: "Hindu: Yellapu" },
  { id: "151", caste: "Muslim: Shia" },
  { id: "152", caste: "Muslim: Sunni" },
  { id: "167", caste: "Sikh: Arora" },
  { id: "472", caste: "Sikh: Bhatia" },
  { id: "155", caste: "Sikh: Gursikh" },
  { id: "156", caste: "Sikh: Jat" },
  { id: "157", caste: "Sikh: Kamboj" },
  { id: "158", caste: "Sikh: Kesadhari" },
  { id: "222", caste: "Sikh: Khashap Rajpoot" },
  { id: "159", caste: "Sikh: Khatri" },
  { id: "172", caste: "Sikh: Labana" },
  { id: "248", caste: "Sikh: Mazhbi" },
  { id: "579", caste: "Sikh: Nai" },
  { id: "580", caste: "Sikh: Prajapati" },
  { id: "644", caste: "Sikh: Rai Sikh" },
  { id: "471", caste: "Sikh: Rajput" },
  { id: "249", caste: "Sikh: Ramdasia" },
  { id: "160", caste: "Sikh: Ramgarhia" },
  { id: "161", caste: "Sikh: Saini" },
  { id: "563", caste: "Sikh: Tonk Kshatriya" },
  { id: "174", caste: "Jain: Digamber" },
  { id: "175", caste: "Jain: Shwetamber" },
];
