export const CastList: {
  religion: string;
  list: { id: number; cast: string }[];
}[] = [
  {
    religion: "Hindu",
    list: [
      { id: 581, cast: "Hindu: 24 Manai Telugu Chettiar" },
      { id: 613, cast: "Hindu: 96K Kokanastha" },
      { id: 278, cast: "Ad Dharmi" },
      { id: 407, cast: "Adi Andhra" },
      { id: 16, cast: "Adi Dravida" },
      { id: 408, cast: "Adi Karnataka" },
      { id: 409, cast: "Agamudayar" },
      { id: 17, cast: "Hindu: Aggarwal" },
      { id: 485, cast: "Hindu: Aggarwal- All" },
      { id: 168, cast: "Agri" },
      { id: 410, cast: "Ahir" },
      { id: 279, cast: "Ahom" },
      { id: 182, cast: "Ambalavasi" },
      { id: 582, cast: "Amma Kodava" },
      { id: 583, cast: "Arakh Arakvanshiya" },
      { id: 584, cast: "Arekatica" },
      { id: 18, cast: "Hindu: Arora" },
      { id: 183, cast: "Arunthathiyar" },
      { id: 19, cast: "Arya Vysya" },
      { id: 487, cast: "Hindu: Arya Vysya- All" },
      { id: 585, cast: "Ayyaraka" },
      { id: 586, cast: "Badaga" },
      { id: 559, cast: "Badhai" },
      { id: 587, cast: "Bagdi" },
      { id: 227, cast: "Baghel Gaderiya" },
      { id: 614, cast: "Bahi" },
      { id: 252, cast: "Baidya" },
      { id: 281, cast: "Baishnab" },
      { id: 282, cast: "Baishya" },
      { id: 648, cast: "Baishya Kapali" },
      { id: 588, cast: "Bajantri" },
      { id: 283, cast: "Balija" },
      { id: 21, cast: "Balija Naidu" },
      { id: 576, cast: "Banayat Oriya" },
      { id: 20, cast: "Hindu: Bania- All" },
      { id: 499, cast: "Bania" },
      { id: 284, cast: "Banik" },
      { id: 491, cast: "Hindu: Banik- All" },
      { id: 411, cast: "Banjara" },
      { id: 589, cast: "Barai" },
      { id: 229, cast: "Bari" },
      { id: 590, cast: "Baria" },
      { id: 285, cast: "Hindu: Barujibi" },
      { id: 569, cast: "Beldar" },
      { id: 286, cast: "Besta" },
      { id: 574, cast: "Bhajantri" },
      { id: 22, cast: "Hindu: Bhandari" },
      { id: 231, cast: "Bhatia" },
      { id: 412, cast: "Bhatraju" },
      { id: 287, cast: "Bhavsar" },
      { id: 288, cast: "Bhovi / Bhoi" },
      { id: 637, cast: "Bhoyar" },
      { id: 591, cast: "Bhulia / Meher" },
      { id: 24, cast: "Billava" },
      { id: 512, cast: "Hindu: Bisa Agarwal" },
      { id: 413, cast: "Bishnoi / Vishnoi" },
      { id: 592, cast: "Bondili" },
      { id: 184, cast: "Boyer" },
      { id: 593, cast: "Brahmakshatriya" },
      { id: 289, cast: "Brahmbatt" },
      { id: 25, cast: "Hindu: Brahmin- All" },
      { id: 500, cast: "Brahmin" },
      { id: 26, cast: "Hindu: Brahmin 6000 Niyogi" },
      { id: 27, cast: "Hindu: Brahmin Anavil" },
      { id: 478, cast: "Hindu: Brahmin Andhra- All" },
      { id: 234, cast: "Hindu: Brahmin Audichya" },
      { id: 414, cast: "Hindu: Brahmin Bajkhedwal" },
      { id: 513, cast: "Hindu: Brahmin Bardai" },
      { id: 290, cast: "Hindu: Brahmin Barendra" },
      { id: 482, cast: "Hindu: Brahmin Bengali- All" },
      { id: 415, cast: "Hindu: Brahmin Bhargava" },
      { id: 291, cast: "Hindu: Brahmin Bhatt" },
      { id: 28, cast: "Hindu: Brahmin Bhumihar" },
      { id: 416, cast: "Hindu: Brahmin Brahacharanam" },
      { id: 514, cast: "Hindu: Brahmin BrahmBhatt" },
      { id: 515, cast: "Hindu: Brahmin Brajastha Maithil" },
      { id: 566, cast: "Hindu: Brahmin Chittpavan Kokanastha" },
      { id: 516, cast: "Hindu: Brahmin Dadhich" },
      { id: 29, cast: "Hindu: Brahmin Daivadnya" },
      { id: 594, cast: "Hindu: Brahmin Danua" },
      { id: 30, cast: "Hindu: Brahmin Deshastha" },
      { id: 545, cast: "Hindu: Brahmin Devrukhe" },
      { id: 292, cast: "Hindu: Brahmin Dhiman" },
      { id: 477, cast: "Hindu: Brahmin Dravida- All" },
      { id: 293, cast: "Hindu: Brahmin Dravida" },
      { id: 294, cast: "Hindu: Brahmin Dunua" },
      { id: 518, cast: "Hindu: Brahmin Embrandiri" },
      { id: 31, cast: "Hindu: Brahmin Garhwali" },
      { id: 32, cast: "Hindu: Brahmin Gaud Saraswat (GSB)" },
      { id: 474, cast: "Hindu: Brahmin Gaur- All" },
      { id: 33, cast: "Hindu: Brahmin Gaur" },
      { id: 34, cast: "Hindu: Brahmin Goswami" },
      { id: 417, cast: "Hindu: Brahmin Gujar Gaur" },
      { id: 480, cast: "Hindu: Brahmin Gujrati- All" },
      { id: 418, cast: "Hindu: Brahmin Gurukkal" },
      { id: 295, cast: "Hindu: Brahmin Halua" },
      { id: 35, cast: "Hindu: Brahmin Havyaka" },
      { id: 296, cast: "Hindu: Brahmin Hoysala" },
      { id: 65, cast: "Hindu: Brahmin Iyengar" },
      { id: 66, cast: "Hindu: Brahmin Iyer" },
      { id: 420, cast: "Hindu: Brahmin Jangid" },
      { id: 421, cast: "Hindu: Brahmin Jangra" },
      { id: 299, cast: "Hindu: Brahmin Jhadua" },
      { id: 262, cast: "Hindu: Brahmin Jhijhotiya" },
      { id: 422, cast: "Hindu: Brahmin Jogi" },
      { id: 519, cast: "Hindu: Brahmin Jyotish" },
      { id: 495, cast: "Hindu: Brahmin Kannada- All" },
      { id: 473, cast: "Hindu: Brahmin Kanyakubj- All" },
      { id: 36, cast: "Hindu: Brahmin Kanyakubj" },
      { id: 37, cast: "Hindu: Brahmin Karhade" },
      { id: 479, cast: "Hindu: Brahmin Karnataka- All" },
      { id: 38, cast: "Hindu: Brahmin Kashmiri Pandit" },
      { id: 520, cast: "Hindu: Brahmin Khadayat" },
      { id: 521, cast: "Hindu: Brahmin Khandelwal" },
      { id: 522, cast: "Hindu: Brahmin Khedaval" },
      { id: 39, cast: "Hindu: Brahmin Koknastha" },
      { id: 300, cast: "Hindu: Brahmin Kota" },
      { id: 301, cast: "Hindu: Brahmin Kulin" },
      { id: 40, cast: "Hindu: Brahmin Kumaoni" },
      { id: 41, cast: "Hindu: Brahmin Madhwa" },
      { id: 481, cast: "Hindu: Brahmin Maharastra- All" },
      { id: 42, cast: "Hindu: Brahmin Maithil" },
      { id: 523, cast: "Hindu: Brahmin Malviya" },
      { id: 547, cast: "Hindu: Brahmin Marwari" },
      { id: 524, cast: "Hindu: Brahmin Mevada" },
      { id: 302, cast: "Hindu: Brahmin Modh" },
      { id: 303, cast: "Hindu: Brahmin Mohyal" },
      { id: 43, cast: "Hindu: Brahmin Nagar" },
      { id: 304, cast: "Hindu: Brahmin Namboodiri" },
      { id: 44, cast: "Hindu: Brahmin Narmadiya" },
      { id: 641, cast: "Hindu: Brahmin Nayi / Nai" },
      { id: 525, cast: "Hindu: Brahmin Paliwal" },
      { id: 306, cast: "Hindu: Brahmin Panda" },
      { id: 307, cast: "Hindu: Brahmin Pandit" },
      { id: 526, cast: "Hindu: Brahmin Panicker" },
      { id: 261, cast: "Hindu: Brahmin Pareek" },
      { id: 237, cast: "Hindu: Brahmin Pushkarna" },
      { id: 483, cast: "Hindu: Brahmin Rajasthani- All" },
      { id: 527, cast: "Hindu: Brahmin Rajgor" },
      { id: 309, cast: "Hindu: Brahmin Rarhi" },
      { id: 45, cast: "Hindu: Brahmin Rigvedi" },
      { id: 310, cast: "Hindu: Brahmin Rudraj" },
      { id: 633, cast: "Hindu: Brahmin Sachora" },
      { id: 311, cast: "Hindu: Brahmin Sakaldwipi" },
      { id: 180, cast: "Hindu: Brahmin Sanadya" },
      { id: 634, cast: "Hindu: Brahmin Sanchihar" },
      { id: 312, cast: "Hindu: Brahmin Sanketi" },
      { id: 475, cast: "Hindu: Brahmin Saraswat- All" },
      { id: 46, cast: "Hindu: Brahmin Saraswat" },
      { id: 546, cast: "Hindu: Brahmin Sarotri" },
      { id: 528, cast: "Hindu: Brahmin Sarua" },
      { id: 47, cast: "Hindu: Brahmin Saryuparin" },
      { id: 251, cast: "Hindu: Brahmin Shivalli" },
      { id: 314, cast: "Hindu: Brahmin Shrimali" },
      { id: 529, cast: "Hindu: Brahmin Sikhwal" },
      { id: 48, cast: "Hindu: Brahmin Smartha" },
      { id: 315, cast: "Hindu: Brahmin Sri Vishnava" },
      { id: 530, cast: "Hindu: Brahmin Stanika" },
      { id: 531, cast: "Hindu: Brahmin Tapodhan" },
      { id: 179, cast: "Hindu: Brahmin Tyagi" },
      { id: 476, cast: "Hindu: Brahmin Utkal- All" },
      { id: 49, cast: "Hindu: Brahmin Vaidiki" },
      { id: 595, cast: "Hindu: Brahmin Vaikhanasa" },
      { id: 532, cast: "Hindu: Brahmin Vaikhawas" },
      { id: 544, cast: "Hindu: Brahmin Vaishnav" },
      { id: 533, cast: "Hindu: Brahmin Valam" },
      { id: 534, cast: "Hindu: Brahmin Velanadu" },
      { id: 402, cast: "Hindu: Brahmin Viswa" },
      { id: 316, cast: "Hindu: Brahmin Vyas" },
      { id: 423, cast: "Hindu: Brahmin Yajurvedi" },
      { id: 535, cast: "Hindu: Brahmin Zalora" },
      { id: 317, cast: "Brahmo" },
      { id: 615, cast: "Buddar" },
      { id: 210, cast: "Bunt Shetty" },
      { id: 616, cast: "Chalawadi / Holeya" },
      { id: 318, cast: "Chamar" },
      { id: 52, cast: "Chambhar" },
      { id: 319, cast: "Chandravanshi Kahar" },
      { id: 596, cast: "Charan" },
      { id: 320, cast: "Chasa" },
      { id: 424, cast: "Chattada Sri Vaishnava" },
      { id: 321, cast: "Chaudary" },
      { id: 53, cast: "Chaurasia" },
      { id: 597, cast: "Chennadasar" },
      { id: 617, cast: "Cheramar" },
      { id: 54, cast: "Chettiar" },
      { id: 488, cast: "Hindu: Chettiar- All" },
      { id: 322, cast: "Chhetri" },
      { id: 618, cast: "Chippolu Mera" },
      { id: 55, cast: "CKP" },
      { id: 56, cast: "Coorgi" },
      { id: 598, cast: "Dasapalanjika Kannada Saineegar" },
      { id: 425, cast: "Hindu: Deshastha Maratha" },
      { id: 230, cast: "Devadigas" },
      { id: 324, cast: "Devang Koshthi" },
      { id: 57, cast: "Devanga" },
      { id: 323, cast: "Devendra Kula Vellalar" },
      { id: 635, cast: "Devipujak (Vaghri)" },
      { id: 58, cast: "Dhangar" },
      { id: 646, cast: "Dhanuk" },
      { id: 171, cast: "Dheevara" },
      { id: 651, cast: "Dhiman" },
      { id: 326, cast: "Dhoba" },
      { id: 166, cast: "Dhobi" },
      { id: 558, cast: "Dhor / Dhoar" },
      { id: 599, cast: "Dommala" },
      { id: 600, cast: "Dumal" },
      { id: 426, cast: "Dusadh" },
      { id: 178, cast: "Edigas" },
      { id: 59, cast: "Ezhava" },
      { id: 185, cast: "Ezhuthachan" },
      { id: 327, cast: "Gabit" },
      { id: 560, cast: "Gangai / Ganesh" },
      { id: 187, cast: "Ganiga" },
      { id: 328, cast: "Garhwali" },
      { id: 601, cast: "Gatti" },
      { id: 247, cast: "Gavali" },
      { id: 602, cast: "Gavandi" },
      { id: 188, cast: "Gavara" },
      { id: 603, cast: "Ghisadi" },
      { id: 329, cast: "Ghumar" },
      { id: 330, cast: "Goala" },
      { id: 331, cast: "Goan" },
      { id: 427, cast: "Hindu: Gomantak Maratha" },
      { id: 548, cast: "Gond Gondi Raj Gond" },
      { id: 428, cast: "Gondhali" },
      { id: 568, cast: "Gopal" },
      { id: 60, cast: "Goud" },
      { id: 61, cast: "Gounder" },
      { id: 62, cast: "Gowda" },
      { id: 429, cast: "Gramani" },
      { id: 332, cast: "Gudia" },
      { id: 63, cast: "Gujjar" },
      { id: 64, cast: "Hindu: Gupta" },
      { id: 652, cast: "Guptan" },
      { id: 430, cast: "Gurav" },
      { id: 561, cast: "Halba Koshti" },
      { id: 223, cast: "Hegde" },
      { id: 604, cast: "Helava" },
      { id: 605, cast: "Jaalari" },
      { id: 70, cast: "Jaiswal" },
      { id: 606, cast: "Jandra" },
      { id: 333, cast: "Jangam" },
      { id: 71, cast: "Jat" },
      { id: 72, cast: "Jatav" },
      { id: 653, cast: "Jetty Malla" },
      { id: 657, cast: "Jingar" },
      { id: 607, cast: "Kachara" },
      { id: 334, cast: "Hindu: Kadava patel" },
      { id: 432, cast: "Kahar" },
      { id: 335, cast: "Kaibarta" },
      { id: 608, cast: "Kaikaala" },
      { id: 619, cast: "Kakkalan" },
      { id: 433, cast: "Kalal" },
      { id: 554, cast: "Kalanji" },
      { id: 74, cast: "Kalar" },
      { id: 654, cast: "Kalinga" },
      { id: 434, cast: "Kalinga Vysya" },
      { id: 609, cast: "Kalita" },
      { id: 337, cast: "Kalwar" },
      { id: 225, cast: "Kamboj" },
      { id: 73, cast: "Kamma" },
      { id: 610, cast: "Kanakkan Padanna" },
      { id: 620, cast: "Kaniyan" },
      { id: 338, cast: "Kansari" },
      { id: 611, cast: "Kansyakaar" },
      { id: 435, cast: "Kapol" },
      { id: 75, cast: "Hindu: Kapu- All" },
      { id: 501, cast: "Kapu" },
      { id: 218, cast: "Kapu Munnuru" },
      { id: 612, cast: "Karakala Bhakthula" },
      { id: 339, cast: "Karana" },
      { id: 340, cast: "Karmakar" },
      { id: 190, cast: "Karuneegar" },
      { id: 341, cast: "Kasar" },
      { id: 342, cast: "Kashyap" },
      { id: 567, cast: "Katiya" },
      { id: 76, cast: "Hindu: Kayastha- All" },
      { id: 502, cast: "Kayastha" },
      { id: 77, cast: "Khandayat" },
      { id: 343, cast: "Hindu: Khandelwal" },
      { id: 551, cast: "Kharvi" },
      { id: 405, cast: "Kharwar" },
      { id: 226, cast: "Khatik" },
      { id: 78, cast: "Khatri" },
      { id: 484, cast: "Hindu: Khatri- All" },
      { id: 562, cast: "Koeri / Koiri" },
      { id: 436, cast: "Hindu: Kokanastha Maratha" },
      { id: 79, cast: "Koli" },
      { id: 437, cast: "Koli Mahadev" },
      { id: 80, cast: "Kongu Vellala Gounder" },
      { id: 344, cast: "Konkani" },
      { id: 564, cast: "Koracha" },
      { id: 621, cast: "Korama" },
      { id: 345, cast: "Kori" },
      { id: 645, cast: "Korvi" },
      { id: 81, cast: "Koshti" },
      { id: 622, cast: "Krishnavaka" },
      { id: 82, cast: "Hindu: Kshatriya- All" },
      { id: 503, cast: "Kshatriya" },
      { id: 217, cast: "Kshatriya Agnikula" },
      { id: 346, cast: "Kudumbi" },
      { id: 191, cast: "Kulalar" },
      { id: 347, cast: "Kulita" },
      { id: 83, cast: "Kumawat" },
      { id: 438, cast: "Kumbhakar" },
      { id: 228, cast: "Kumhar / Kumbhar" },
      { id: 192, cast: "Kummari" },
      { id: 84, cast: "Kunbi" },
      { id: 85, cast: "Kurmi" },
      { id: 349, cast: "Kurmi Kshatriya" },
      { id: 86, cast: "Kuruba" },
      { id: 350, cast: "Kuruhina Shetty" },
      { id: 193, cast: "Kurumbar" },
      { id: 87, cast: "Kushwaha" },
      { id: 351, cast: "Kutchi" },
      { id: 439, cast: "Kutchi Gurjar" },
      { id: 352, cast: "Lambadi" },
      { id: 649, cast: "Laxminarayan gola" },
      { id: 88, cast: "Leva Patidar" },
      { id: 354, cast: "Leva Patil" },
      { id: 89, cast: "Lingayat" },
      { id: 440, cast: "Hindu: Lodhi Rajput" },
      { id: 90, cast: "Lohana" },
      { id: 250, cast: "Lohar" },
      { id: 355, cast: "Lubana" },
      { id: 194, cast: "Madiga" },
      { id: 356, cast: "Hindu: Mahajan" },
      { id: 357, cast: "Mahar" },
      { id: 623, cast: "Mahendra" },
      { id: 91, cast: "Maheshwari" },
      { id: 358, cast: "Mahindra" },
      { id: 92, cast: "Mahisya" },
      { id: 359, cast: "Majabi Mazhbi" },
      { id: 195, cast: "Mala" },
      { id: 93, cast: "Mali" },
      { id: 164, cast: "Mallah" },
      { id: 573, cast: "Manikpuri" },
      { id: 360, cast: "Manipuri" },
      { id: 557, cast: "Manjhi" },
      { id: 361, cast: "Mapila" },
      { id: 94, cast: "Maratha" },
      { id: 494, cast: "Hindu: Maratha- All" },
      { id: 441, cast: "Maravar" },
      { id: 197, cast: "Maruthuvar" },
      { id: 95, cast: "Hindu: Marwari" },
      { id: 486, cast: "Hindu: Marwari- All" },
      { id: 362, cast: "Matang" },
      { id: 442, cast: "Hindu: Mathur" },
      { id: 96, cast: "Maurya" },
      { id: 364, cast: "Meena" },
      { id: 198, cast: "Meenavar" },
      { id: 365, cast: "Mehra" },
      { id: 97, cast: "Menon" },
      { id: 170, cast: "Meru" },
      { id: 366, cast: "Meru darji" },
      { id: 367, cast: "Modak" },
      { id: 100, cast: "Mogaveera" },
      { id: 235, cast: "Monchi" },
      { id: 443, cast: "Motati Reddy" },
      { id: 98, cast: "Hindu: Mudaliar- All" },
      { id: 504, cast: "Mudaliar" },
      { id: 99, cast: "Mudaliar Arcot" },
      { id: 199, cast: "Mudiraj" },
      { id: 201, cast: "Muthuraja" },
      { id: 625, cast: "Naagavamsam" },
      { id: 101, cast: "Nadar" },
      { id: 626, cast: "Nagaralu" },
      { id: 202, cast: "Naicker" },
      { id: 102, cast: "Naidu" },
      { id: 233, cast: "Naik Nayak Nayaka" },
      { id: 103, cast: "Hindu: Nair- All" },
      { id: 505, cast: "Nair" },
      { id: 400, cast: "Nair Veluthedathu" },
      { id: 401, cast: "Nair Vilakkithala" },
      { id: 253, cast: "Namasudra / Namosudra" },
      { id: 104, cast: "Nambiar" },
      { id: 655, cast: "Nambisan" },
      { id: 105, cast: "Namboodiri" },
      { id: 572, cast: "Namdev Chhipa" },
      { id: 638, cast: "Nandiwale" },
      { id: 369, cast: "Napit" },
      { id: 553, cast: "Nath Jogi" },
      { id: 107, cast: "Nayee (Barber)" },
      { id: 106, cast: "Nepali" },
      { id: 647, cast: "Nessi / Kurni" },
      { id: 370, cast: "Nhavi" },
      { id: 555, cast: "Nonia" },
      { id: 470, cast: "OBC" },
      { id: 643, cast: "Odan" },
      { id: 371, cast: "Oswal" },
      { id: 627, cast: "Otari" },
      { id: 108, cast: "Padmashali" },
      { id: 372, cast: "Pal" },
      { id: 373, cast: "Panchal" },
      { id: 444, cast: "Panchamsali" },
      { id: 445, cast: "Pandaram" },
      { id: 204, cast: "Panicker" },
      { id: 205, cast: "Parkava Kulam" },
      { id: 640, cast: "Parvatha Rajakulam" },
      { id: 374, cast: "Pasi" },
      { id: 109, cast: "Hindu: Patel- All" },
      { id: 506, cast: "Patel" },
      { id: 176, cast: "patel Dodia" },
      { id: 110, cast: "patel Kadva" },
      { id: 111, cast: "patel Leva" },
      { id: 543, cast: "Patel Lodhi" },
      { id: 571, cast: "Pathare Prabhu" },
      { id: 112, cast: "Hindu: Patil- All" },
      { id: 507, cast: "Hindu: Patil" },
      { id: 206, cast: "Patnaick" },
      { id: 375, cast: "Patra" },
      { id: 446, cast: "Perika" },
      { id: 114, cast: "Pillai" },
      { id: 628, cast: "Poosala" },
      { id: 115, cast: "Prajapati" },
      { id: 578, cast: "Rabari" },
      { id: 447, cast: "Raigar" },
      { id: 556, cast: "Raikwar" },
      { id: 207, cast: "Rajaka" },
      { id: 448, cast: "Rajbhar" },
      { id: 376, cast: "Rajbongshi" },
      { id: 550, cast: "Rajpurohit" },
      { id: 116, cast: "Hindu: Rajput- All" },
      { id: 508, cast: "Rajput" },
      { id: 117, cast: "Rajput Garhwali" },
      { id: 118, cast: "Rajput Kumaoni" },
      { id: 449, cast: "Hindu: Rajput Negi" },
      { id: 221, cast: "Rajput Rohella Tank" },
      { id: 377, cast: "Ramdasia" },
      { id: 378, cast: "Ramgarhia" },
      { id: 549, cast: "Ramoshi Berad Bedar" },
      { id: 379, cast: "Ravidasia" },
      { id: 380, cast: "Rawat" },
      { id: 119, cast: "Reddy" },
      { id: 639, cast: "Ror" },
      { id: 120, cast: "Sadgope" },
      { id: 381, cast: "Saha" },
      { id: 382, cast: "Sahu" },
      { id: 177, cast: "Saini" },
      { id: 208, cast: "Saliya" },
      { id: 570, cast: "Sathwara" },
      { id: 656, cast: "Savji" },
      { id: 565, cast: "Sawantwadi" },
      { id: 121, cast: "Scheduled Caste" },
      { id: 489, cast: "Hindu: Scheduled Caste- All" },
      { id: 403, cast: "Scheduled Tribe" },
      { id: 490, cast: "Hindu: Scheduled Tribe- All" },
      { id: 209, cast: "Senai Thalaivar" },
      { id: 450, cast: "Senguntha Mudaliyar" },
      { id: 383, cast: "Settibalija" },
      { id: 165, cast: "Shah" },
      { id: 122, cast: "Shimpi" },
      { id: 123, cast: "Sindhi" },
      { id: 492, cast: "Hindu: Sindhi- All" },
      { id: 451, cast: "Hindu: Sindhi Amil" },
      { id: 452, cast: "Hindu: Sindhi Baibhand" },
      { id: 511, cast: "Hindu: Sindhi Bhanusali" },
      { id: 453, cast: "Hindu: Sindhi Bhatia" },
      { id: 536, cast: "Hindu: Sindhi Chhapru" },
      { id: 542, cast: "Hindu: Sindhi Daru" },
      { id: 537, cast: "Hindu: Sindhi Hydrabadi" },
      { id: 454, cast: "Hindu: Sindhi Larai" },
      { id: 538, cast: "Hindu: Sindhi Larkan" },
      { id: 455, cast: "Hindu: Sindhi Larkana" },
      { id: 539, cast: "Hindu: Sindhi Lohana" },
      { id: 456, cast: "Hindu: Sindhi Rohiri" },
      { id: 457, cast: "Hindu: Sindhi Sahiti" },
      { id: 458, cast: "Hindu: Sindhi Sakkhar" },
      { id: 540, cast: "Hindu: Sindhi Sehwani" },
      { id: 459, cast: "Hindu: Sindhi Shikarpuri" },
      { id: 541, cast: "Hindu: Sindhi Thatai" },
      { id: 460, cast: "SKP" },
      { id: 124, cast: "Somvanshi" },
      { id: 241, cast: "Somvanshi Kayastha Prabhu" },
      { id: 125, cast: "Sonar / Sunar" },
      { id: 384, cast: "Hindu: Soni" },
      { id: 461, cast: "Hindu: Sood" },
      { id: 211, cast: "Sourashtra" },
      { id: 126, cast: "Sozhiya Vellalar" },
      { id: 232, cast: "Srisayani" },
      { id: 239, cast: "SSK" },
      { id: 385, cast: "Subarna Banik" },
      { id: 386, cast: "Sudi Suri Sundhi Shaundik" },
      { id: 127, cast: "Sutar" },
      { id: 387, cast: "Swakula sali" },
      { id: 128, cast: "Swarnkar" },
      { id: 388, cast: "Tamboli" },
      { id: 650, cast: "Tammali" },
      { id: 389, cast: "Tanti" },
      { id: 163, cast: "Tantuway" },
      { id: 212, cast: "Telaga" },
      { id: 129, cast: "Teli" },
      { id: 493, cast: "Hindu: Teli- All" },
      { id: 390, cast: "Thakkar" },
      { id: 391, cast: "Hindu: Thakur" },
      { id: 642, cast: "Tharakan" },
      { id: 130, cast: "Thevar Mukkulathor" },
      { id: 392, cast: "Thigala" },
      { id: 131, cast: "Thiyya" },
      { id: 462, cast: "Tili" },
      { id: 463, cast: "Togata" },
      { id: 464, cast: "Tonk Kshatriya" },
      { id: 393, cast: "Tribe" },
      { id: 465, cast: "Turupu Kapu" },
      { id: 394, cast: "Uppara" },
      { id: 577, cast: "Vadar" },
      { id: 395, cast: "Vaddera" },
      { id: 466, cast: "Vaidiki Velanadu" },
      { id: 133, cast: "Vaish" },
      { id: 134, cast: "Hindu: Vaishnav- All" },
      { id: 509, cast: "Vaishnav" },
      { id: 135, cast: "Vaishnav Vanik" },
      { id: 396, cast: "Vaishnava" },
      { id: 136, cast: "Vaishya" },
      { id: 397, cast: "Vaishya Vani" },
      { id: 629, cast: "Vallala" },
      { id: 467, cast: "Valluvar" },
      { id: 137, cast: "Valmiki" },
      { id: 398, cast: "Vania" },
      { id: 399, cast: "Vaniya" },
      { id: 630, cast: "Vanjara" },
      { id: 224, cast: "Vanjari" },
      { id: 236, cast: "Vankar" },
      { id: 213, cast: "Vannar" },
      { id: 214, cast: "Vannia Kula Kshatriyar" },
      { id: 138, cast: "Vanniyar" },
      { id: 624, cast: "Variar" },
      { id: 139, cast: "Varshney" },
      { id: 215, cast: "Veershaiva Veera Saivam" },
      { id: 631, cast: "Velaan" },
      { id: 142, cast: "Velama" },
      { id: 468, cast: "Velan" },
      { id: 141, cast: "Hindu: Vellalar- All" },
      { id: 510, cast: "Vellalar" },
      { id: 469, cast: "Vettuva Gounder" },
      { id: 143, cast: "Vishwakarma" },
      { id: 144, cast: "Vokkaliga" },
      { id: 145, cast: "Vysya" },
      { id: 575, cast: "Wani" },
      { id: 146, cast: "Yadav / Yadava" },
      { id: 632, cast: "Yellapu" },
    ],
  },
  {
    religion: "Muslim",
    list: [
      { id: 151, cast: "Muslim: Shia" },
      { id: 152, cast: "Muslim: Sunni" },
    ],
  },
  {
    religion: "Sikh",
    list: [
      { id: 167, cast: "Arora" },
      { id: 472, cast: "Bhatia" },
      { id: 155, cast: "Gursikh" },
      { id: 156, cast: "Jat" },
      { id: 157, cast: "Kamboj" },
      { id: 158, cast: "Kesadhari" },
      { id: 222, cast: "Khashap Rajpoot" },
      { id: 159, cast: "Khatri" },
      { id: 172, cast: "Labana" },
      { id: 248, cast: "Mazhbi" },
      { id: 579, cast: "Nai" },
      { id: 580, cast: "Prajapati" },
      { id: 644, cast: "Rai Sikh" },
      { id: 471, cast: "Rajput" },
      { id: 249, cast: "Ramdasia" },
      { id: 160, cast: "Ramgarhia" },
      { id: 161, cast: "Saini" },
      { id: 563, cast: "Tonk Kshatriya" },
    ],
  },
  {
    religion: "Jain",
    list: [
      { id: 174, cast: "Digamber" },
      { id: 175, cast: "Shwetamber" },
    ],
  },
];
