export type ICastListArray = { id: string; caste: string };
export const CastListArray = [
  { id: "581", caste: "Hindu: 24 Manai Telugu Chettiar" },
  { id: "613", caste: "Hindu: 96K Kokanastha" },
  { id: "278", caste: "Ad Dharmi" },
  { id: "407", caste: "Adi Andhra" },
  { id: "16", caste: "Adi Dravida" },
  { id: "408", caste: "Adi Karnataka" },
  { id: "409", caste: "Agamudayar" },
  { id: "17", caste: "Hindu: Aggarwal" },
  { id: "485", caste: "Hindu: Aggarwal- All" },
  { id: "168", caste: "Agri" },
  { id: "410", caste: "Ahir" },
  { id: "279", caste: "Ahom" },
  { id: "182", caste: "Ambalavasi" },
  { id: "582", caste: "Amma Kodava" },
  { id: "583", caste: "Arakh Arakvanshiya" },
  { id: "584", caste: "Arekatica" },
  { id: "18", caste: "Hindu: Arora" },
  { id: "183", caste: "Arunthathiyar" },
  { id: "19", caste: "Arya Vysya" },
  { id: "487", caste: "Hindu: Arya Vysya- All" },
  { id: "585", caste: "Ayyaraka" },
  { id: "586", caste: "Badaga" },
  { id: "559", caste: "Badhai" },
  { id: "587", caste: "Bagdi" },
  { id: "227", caste: "Baghel Gaderiya" },
  { id: "614", caste: "Bahi" },
  { id: "252", caste: "Baidya" },
  { id: "281", caste: "Baishnab" },
  { id: "282", caste: "Baishya" },
  { id: "648", caste: "Baishya Kapali" },
  { id: "588", caste: "Bajantri" },
  { id: "283", caste: "Balija" },
  { id: "21", caste: "Balija Naidu" },
  { id: "576", caste: "Banayat Oriya" },
  { id: "20", caste: "Hindu: Bania- All" },
  { id: "499", caste: "Bania" },
  { id: "284", caste: "Banik" },
  { id: "491", caste: "Hindu: Banik- All" },
  { id: "411", caste: "Banjara" },
  { id: "589", caste: "Barai" },
  { id: "229", caste: "Bari" },
  { id: "590", caste: "Baria" },
  { id: "285", caste: "Hindu: Barujibi" },
  { id: "569", caste: "Beldar" },
  { id: "286", caste: "Besta" },
  { id: "574", caste: "Bhajantri" },
  { id: "22", caste: "Hindu: Bhandari" },
  { id: "231", caste: "Bhatia" },
  { id: "412", caste: "Bhatraju" },
  { id: "287", caste: "Bhavsar" },
  { id: "288", caste: "Bhovi / Bhoi" },
  { id: "637", caste: "Bhoyar" },
  { id: "591", caste: "Bhulia / Meher" },
  { id: "24", caste: "Billava" },
  { id: "512", caste: "Hindu: Bisa Agarwal" },
  { id: "413", caste: "Bishnoi / Vishnoi" },
  { id: "592", caste: "Bondili" },
  { id: "184", caste: "Boyer" },
  { id: "593", caste: "Brahmakshatriya" },
  { id: "289", caste: "Brahmbatt" },
  { id: "25", caste: "Hindu: Brahmin- All" },
  { id: "500", caste: "Brahmin" },
  { id: "26", caste: "Hindu: Brahmin 6000 Niyogi" },
  { id: "27", caste: "Hindu: Brahmin Anavil" },
  { id: "478", caste: "Hindu: Brahmin Andhra- All" },
  { id: "234", caste: "Hindu: Brahmin Audichya" },
  { id: "414", caste: "Hindu: Brahmin Bajkhedwal" },
  { id: "513", caste: "Hindu: Brahmin Bardai" },
  { id: "290", caste: "Hindu: Brahmin Barendra" },
  { id: "482", caste: "Hindu: Brahmin Bengali- All" },
  { id: "415", caste: "Hindu: Brahmin Bhargava" },
  { id: "291", caste: "Hindu: Brahmin Bhatt" },
  { id: "28", caste: "Hindu: Brahmin Bhumihar" },
  { id: "416", caste: "Hindu: Brahmin Brahacharanam" },
  { id: "514", caste: "Hindu: Brahmin BrahmBhatt" },
  { id: "515", caste: "Hindu: Brahmin Brajastha Maithil" },
  { id: "566", caste: "Hindu: Brahmin Chittpavan Kokanastha" },
  { id: "516", caste: "Hindu: Brahmin Dadhich" },
  { id: "29", caste: "Hindu: Brahmin Daivadnya" },
  { id: "594", caste: "Hindu: Brahmin Danua" },
  { id: "30", caste: "Hindu: Brahmin Deshastha" },
  { id: "545", caste: "Hindu: Brahmin Devrukhe" },
  { id: "292", caste: "Hindu: Brahmin Dhiman" },
  { id: "477", caste: "Hindu: Brahmin Dravida- All" },
  { id: "293", caste: "Hindu: Brahmin Dravida" },
  { id: "294", caste: "Hindu: Brahmin Dunua" },
  { id: "518", caste: "Hindu: Brahmin Embrandiri" },
  { id: "31", caste: "Hindu: Brahmin Garhwali" },
  { id: "32", caste: "Hindu: Brahmin Gaud Saraswat (GSB)" },
  { id: "474", caste: "Hindu: Brahmin Gaur- All" },
  { id: "33", caste: "Hindu: Brahmin Gaur" },
  { id: "34", caste: "Hindu: Brahmin Goswami" },
  { id: "417", caste: "Hindu: Brahmin Gujar Gaur" },
  { id: "480", caste: "Hindu: Brahmin Gujrati- All" },
  { id: "418", caste: "Hindu: Brahmin Gurukkal" },
  { id: "295", caste: "Hindu: Brahmin Halua" },
  { id: "35", caste: "Hindu: Brahmin Havyaka" },
  { id: "296", caste: "Hindu: Brahmin Hoysala" },
  { id: "65", caste: "Hindu: Brahmin Iyengar" },
  { id: "66", caste: "Hindu: Brahmin Iyer" },
  { id: "420", caste: "Hindu: Brahmin Jangid" },
  { id: "421", caste: "Hindu: Brahmin Jangra" },
  { id: "299", caste: "Hindu: Brahmin Jhadua" },
  { id: "262", caste: "Hindu: Brahmin Jhijhotiya" },
  { id: "422", caste: "Hindu: Brahmin Jogi" },
  { id: "519", caste: "Hindu: Brahmin Jyotish" },
  { id: "495", caste: "Hindu: Brahmin Kannada- All" },
  { id: "473", caste: "Hindu: Brahmin Kanyakubj- All" },
  { id: "36", caste: "Hindu: Brahmin Kanyakubj" },
  { id: "37", caste: "Hindu: Brahmin Karhade" },
  { id: "479", caste: "Hindu: Brahmin Karnataka- All" },
  { id: "38", caste: "Hindu: Brahmin Kashmiri Pandit" },
  { id: "520", caste: "Hindu: Brahmin Khadayat" },
  { id: "521", caste: "Hindu: Brahmin Khandelwal" },
  { id: "522", caste: "Hindu: Brahmin Khedaval" },
  { id: "39", caste: "Hindu: Brahmin Koknastha" },
  { id: "300", caste: "Hindu: Brahmin Kota" },
  { id: "301", caste: "Hindu: Brahmin Kulin" },
  { id: "40", caste: "Hindu: Brahmin Kumaoni" },
  { id: "41", caste: "Hindu: Brahmin Madhwa" },
  { id: "481", caste: "Hindu: Brahmin Maharastra- All" },
  { id: "42", caste: "Hindu: Brahmin Maithil" },
  { id: "523", caste: "Hindu: Brahmin Malviya" },
  { id: "547", caste: "Hindu: Brahmin Marwari" },
  { id: "524", caste: "Hindu: Brahmin Mevada" },
  { id: "302", caste: "Hindu: Brahmin Modh" },
  { id: "303", caste: "Hindu: Brahmin Mohyal" },
  { id: "43", caste: "Hindu: Brahmin Nagar" },
  { id: "304", caste: "Hindu: Brahmin Namboodiri" },
  { id: "44", caste: "Hindu: Brahmin Narmadiya" },
  { id: "641", caste: "Hindu: Brahmin Nayi / Nai" },
  { id: "525", caste: "Hindu: Brahmin Paliwal" },
  { id: "306", caste: "Hindu: Brahmin Panda" },
  { id: "307", caste: "Hindu: Brahmin Pandit" },
  { id: "526", caste: "Hindu: Brahmin Panicker" },
  { id: "261", caste: "Hindu: Brahmin Pareek" },
  { id: "237", caste: "Hindu: Brahmin Pushkarna" },
  { id: "483", caste: "Hindu: Brahmin Rajasthani- All" },
  { id: "527", caste: "Hindu: Brahmin Rajgor" },
  { id: "309", caste: "Hindu: Brahmin Rarhi" },
  { id: "45", caste: "Hindu: Brahmin Rigvedi" },
  { id: "310", caste: "Hindu: Brahmin Rudraj" },
  { id: "633", caste: "Hindu: Brahmin Sachora" },
  { id: "311", caste: "Hindu: Brahmin Sakaldwipi" },
  { id: "180", caste: "Hindu: Brahmin Sanadya" },
  { id: "634", caste: "Hindu: Brahmin Sanchihar" },
  { id: "312", caste: "Hindu: Brahmin Sanketi" },
  { id: "475", caste: "Hindu: Brahmin Saraswat- All" },
  { id: "46", caste: "Hindu: Brahmin Saraswat" },
  { id: "546", caste: "Hindu: Brahmin Sarotri" },
  { id: "528", caste: "Hindu: Brahmin Sarua" },
  { id: "47", caste: "Hindu: Brahmin Saryuparin" },
  { id: "251", caste: "Hindu: Brahmin Shivalli" },
  { id: "314", caste: "Hindu: Brahmin Shrimali" },
  { id: "529", caste: "Hindu: Brahmin Sikhwal" },
  { id: "48", caste: "Hindu: Brahmin Smartha" },
  { id: "315", caste: "Hindu: Brahmin Sri Vishnava" },
  { id: "530", caste: "Hindu: Brahmin Stanika" },
  { id: "531", caste: "Hindu: Brahmin Tapodhan" },
  { id: "179", caste: "Hindu: Brahmin Tyagi" },
  { id: "476", caste: "Hindu: Brahmin Utkal- All" },
  { id: "49", caste: "Hindu: Brahmin Vaidiki" },
  { id: "595", caste: "Hindu: Brahmin Vaikhanasa" },
  { id: "532", caste: "Hindu: Brahmin Vaikhawas" },
  { id: "544", caste: "Hindu: Brahmin Vaishnav" },
  { id: "533", caste: "Hindu: Brahmin Valam" },
  { id: "534", caste: "Hindu: Brahmin Velanadu" },
  { id: "402", caste: "Hindu: Brahmin Viswa" },
  { id: "316", caste: "Hindu: Brahmin Vyas" },
  { id: "423", caste: "Hindu: Brahmin Yajurvedi" },
  { id: "535", caste: "Hindu: Brahmin Zalora" },
  { id: "317", caste: "Brahmo" },
  { id: "615", caste: "Buddar" },
  { id: "210", caste: "Bunt Shetty" },
  { id: "616", caste: "Chalawadi / Holeya" },
  { id: "318", caste: "Chamar" },
  { id: "52", caste: "Chambhar" },
  { id: "319", caste: "Chandravanshi Kahar" },
  { id: "596", caste: "Charan" },
  { id: "320", caste: "Chasa" },
  { id: "424", caste: "Chattada Sri Vaishnava" },
  { id: "321", caste: "Chaudary" },
  { id: "53", caste: "Chaurasia" },
  { id: "597", caste: "Chennadasar" },
  { id: "617", caste: "Cheramar" },
  { id: "54", caste: "Chettiar" },
  { id: "488", caste: "Hindu: Chettiar- All" },
  { id: "322", caste: "Chhetri" },
  { id: "618", caste: "Chippolu Mera" },
  { id: "55", caste: "CKP" },
  { id: "56", caste: "Coorgi" },
  { id: "598", caste: "Dasapalanjika Kannada Saineegar" },
  { id: "425", caste: "Hindu: Deshastha Maratha" },
  { id: "230", caste: "Devadigas" },
  { id: "324", caste: "Devang Koshthi" },
  { id: "57", caste: "Devanga" },
  { id: "323", caste: "Devendra Kula Vellalar" },
  { id: "635", caste: "Devipujak (Vaghri)" },
  { id: "58", caste: "Dhangar" },
  { id: "646", caste: "Dhanuk" },
  { id: "171", caste: "Dheevara" },
  { id: "651", caste: "Dhiman" },
  { id: "326", caste: "Dhoba" },
  { id: "166", caste: "Dhobi" },
  { id: "558", caste: "Dhor / Dhoar" },
  { id: "599", caste: "Dommala" },
  { id: "600", caste: "Dumal" },
  { id: "426", caste: "Dusadh" },
  { id: "178", caste: "Edigas" },
  { id: "59", caste: "Ezhava" },
  { id: "185", caste: "Ezhuthachan" },
  { id: "327", caste: "Gabit" },
  { id: "560", caste: "Gangai / Ganesh" },
  { id: "187", caste: "Ganiga" },
  { id: "328", caste: "Garhwali" },
  { id: "601", caste: "Gatti" },
  { id: "247", caste: "Gavali" },
  { id: "602", caste: "Gavandi" },
  { id: "188", caste: "Gavara" },
  { id: "603", caste: "Ghisadi" },
  { id: "329", caste: "Ghumar" },
  { id: "330", caste: "Goala" },
  { id: "331", caste: "Goan" },
  { id: "427", caste: "Hindu: Gomantak Maratha" },
  { id: "548", caste: "Gond Gondi Raj Gond" },
  { id: "428", caste: "Gondhali" },
  { id: "568", caste: "Gopal" },
  { id: "60", caste: "Goud" },
  { id: "61", caste: "Gounder" },
  { id: "62", caste: "Gowda" },
  { id: "429", caste: "Gramani" },
  { id: "332", caste: "Gudia" },
  { id: "63", caste: "Gujjar" },
  { id: "64", caste: "Hindu: Gupta" },
  { id: "652", caste: "Guptan" },
  { id: "430", caste: "Gurav" },
  { id: "561", caste: "Halba Koshti" },
  { id: "223", caste: "Hegde" },
  { id: "604", caste: "Helava" },
  { id: "605", caste: "Jaalari" },
  { id: "70", caste: "Jaiswal" },
  { id: "606", caste: "Jandra" },
  { id: "333", caste: "Jangam" },
  { id: "71", caste: "Jat" },
  { id: "72", caste: "Jatav" },
  { id: "653", caste: "Jetty Malla" },
  { id: "657", caste: "Jingar" },
  { id: "607", caste: "Kachara" },
  { id: "334", caste: "Hindu: Kadava patel" },
  { id: "432", caste: "Kahar" },
  { id: "335", caste: "Kaibarta" },
  { id: "608", caste: "Kaikaala" },
  { id: "619", caste: "Kakkalan" },
  { id: "433", caste: "Kalal" },
  { id: "554", caste: "Kalanji" },
  { id: "74", caste: "Kalar" },
  { id: "654", caste: "Kalinga" },
  { id: "434", caste: "Kalinga Vysya" },
  { id: "609", caste: "Kalita" },
  { id: "337", caste: "Kalwar" },
  { id: "225", caste: "Kamboj" },
  { id: "73", caste: "Kamma" },
  { id: "610", caste: "Kanakkan Padanna" },
  { id: "620", caste: "Kaniyan" },
  { id: "338", caste: "Kansari" },
  { id: "611", caste: "Kansyakaar" },
  { id: "435", caste: "Kapol" },
  { id: "75", caste: "Hindu: Kapu- All" },
  { id: "501", caste: "Kapu" },
  { id: "218", caste: "Kapu Munnuru" },
  { id: "612", caste: "Karakala Bhakthula" },
  { id: "339", caste: "Karana" },
  { id: "340", caste: "Karmakar" },
  { id: "190", caste: "Karuneegar" },
  { id: "341", caste: "Kasar" },
  { id: "342", caste: "Kashyap" },
  { id: "567", caste: "Katiya" },
  { id: "76", caste: "Hindu: Kayastha- All" },
  { id: "502", caste: "Kayastha" },
  { id: "77", caste: "Khandayat" },
  { id: "343", caste: "Hindu: Khandelwal" },
  { id: "551", caste: "Kharvi" },
  { id: "405", caste: "Kharwar" },
  { id: "226", caste: "Khatik" },
  { id: "78", caste: "Khatri" },
  { id: "484", caste: "Hindu: Khatri- All" },
  { id: "562", caste: "Koeri / Koiri" },
  { id: "436", caste: "Hindu: Kokanastha Maratha" },
  { id: "79", caste: "Koli" },
  { id: "437", caste: "Koli Mahadev" },
  { id: "80", caste: "Kongu Vellala Gounder" },
  { id: "344", caste: "Konkani" },
  { id: "564", caste: "Koracha" },
  { id: "621", caste: "Korama" },
  { id: "345", caste: "Kori" },
  { id: "645", caste: "Korvi" },
  { id: "81", caste: "Koshti" },
  { id: "622", caste: "Krishnavaka" },
  { id: "82", caste: "Hindu: Kshatriya- All" },
  { id: "503", caste: "Kshatriya" },
  { id: "217", caste: "Kshatriya Agnikula" },
  { id: "346", caste: "Kudumbi" },
  { id: "191", caste: "Kulalar" },
  { id: "347", caste: "Kulita" },
  { id: "83", caste: "Kumawat" },
  { id: "438", caste: "Kumbhakar" },
  { id: "228", caste: "Kumhar / Kumbhar" },
  { id: "192", caste: "Kummari" },
  { id: "84", caste: "Kunbi" },
  { id: "85", caste: "Kurmi" },
  { id: "349", caste: "Kurmi Kshatriya" },
  { id: "86", caste: "Kuruba" },
  { id: "350", caste: "Kuruhina Shetty" },
  { id: "193", caste: "Kurumbar" },
  { id: "87", caste: "Kushwaha" },
  { id: "351", caste: "Kutchi" },
  { id: "439", caste: "Kutchi Gurjar" },
  { id: "352", caste: "Lambadi" },
  { id: "649", caste: "Laxminarayan gola" },
  { id: "88", caste: "Leva Patidar" },
  { id: "354", caste: "Leva Patil" },
  { id: "89", caste: "Lingayat" },
  { id: "440", caste: "Hindu: Lodhi Rajput" },
  { id: "90", caste: "Lohana" },
  { id: "250", caste: "Lohar" },
  { id: "355", caste: "Lubana" },
  { id: "194", caste: "Madiga" },
  { id: "356", caste: "Hindu: Mahajan" },
  { id: "357", caste: "Mahar" },
  { id: "623", caste: "Mahendra" },
  { id: "91", caste: "Maheshwari" },
  { id: "358", caste: "Mahindra" },
  { id: "92", caste: "Mahisya" },
  { id: "359", caste: "Majabi Mazhbi" },
  { id: "195", caste: "Mala" },
  { id: "93", caste: "Mali" },
  { id: "164", caste: "Mallah" },
  { id: "573", caste: "Manikpuri" },
  { id: "360", caste: "Manipuri" },
  { id: "557", caste: "Manjhi" },
  { id: "361", caste: "Mapila" },
  { id: "94", caste: "Maratha" },
  { id: "494", caste: "Hindu: Maratha- All" },
  { id: "441", caste: "Maravar" },
  { id: "197", caste: "Maruthuvar" },
  { id: "95", caste: "Hindu: Marwari" },
  { id: "486", caste: "Hindu: Marwari- All" },
  { id: "362", caste: "Matang" },
  { id: "442", caste: "Hindu: Mathur" },
  { id: "96", caste: "Maurya" },
  { id: "364", caste: "Meena" },
  { id: "198", caste: "Meenavar" },
  { id: "365", caste: "Mehra" },
  { id: "97", caste: "Menon" },
  { id: "170", caste: "Meru" },
  { id: "366", caste: "Meru darji" },
  { id: "367", caste: "Modak" },
  { id: "100", caste: "Mogaveera" },
  { id: "235", caste: "Monchi" },
  { id: "443", caste: "Motati Reddy" },
  { id: "98", caste: "Hindu: Mudaliar- All" },
  { id: "504", caste: "Mudaliar" },
  { id: "99", caste: "Mudaliar Arcot" },
  { id: "199", caste: "Mudiraj" },
  { id: "201", caste: "Muthuraja" },
  { id: "625", caste: "Naagavamsam" },
  { id: "101", caste: "Nadar" },
  { id: "626", caste: "Nagaralu" },
  { id: "202", caste: "Naicker" },
  { id: "102", caste: "Naidu" },
  { id: "233", caste: "Naik Nayak Nayaka" },
  { id: "103", caste: "Hindu: Nair- All" },
  { id: "505", caste: "Nair" },
  { id: "400", caste: "Nair Veluthedathu" },
  { id: "401", caste: "Nair Vilakkithala" },
  { id: "253", caste: "Namasudra / Namosudra" },
  { id: "104", caste: "Nambiar" },
  { id: "655", caste: "Nambisan" },
  { id: "105", caste: "Namboodiri" },
  { id: "572", caste: "Namdev Chhipa" },
  { id: "638", caste: "Nandiwale" },
  { id: "369", caste: "Napit" },
  { id: "553", caste: "Nath Jogi" },
  { id: "107", caste: "Nayee (Barber)" },
  { id: "106", caste: "Nepali" },
  { id: "647", caste: "Nessi / Kurni" },
  { id: "370", caste: "Nhavi" },
  { id: "555", caste: "Nonia" },
  { id: "470", caste: "OBC" },
  { id: "643", caste: "Odan" },
  { id: "371", caste: "Oswal" },
  { id: "627", caste: "Otari" },
  { id: "108", caste: "Padmashali" },
  { id: "372", caste: "Pal" },
  { id: "373", caste: "Panchal" },
  { id: "444", caste: "Panchamsali" },
  { id: "445", caste: "Pandaram" },
  { id: "204", caste: "Panicker" },
  { id: "205", caste: "Parkava Kulam" },
  { id: "640", caste: "Parvatha Rajakulam" },
  { id: "374", caste: "Pasi" },
  { id: "109", caste: "Hindu: Patel- All" },
  { id: "506", caste: "Patel" },
  { id: "176", caste: "patel Dodia" },
  { id: "110", caste: "patel Kadva" },
  { id: "111", caste: "patel Leva" },
  { id: "543", caste: "Patel Lodhi" },
  { id: "571", caste: "Pathare Prabhu" },
  { id: "112", caste: "Hindu: Patil- All" },
  { id: "507", caste: "Hindu: Patil" },
  { id: "206", caste: "Patnaick" },
  { id: "375", caste: "Patra" },
  { id: "446", caste: "Perika" },
  { id: "114", caste: "Pillai" },
  { id: "628", caste: "Poosala" },
  { id: "115", caste: "Prajapati" },
  { id: "578", caste: "Rabari" },
  { id: "447", caste: "Raigar" },
  { id: "556", caste: "Raikwar" },
  { id: "207", caste: "Rajaka" },
  { id: "448", caste: "Rajbhar" },
  { id: "376", caste: "Rajbongshi" },
  { id: "550", caste: "Rajpurohit" },
  { id: "116", caste: "Hindu: Rajput- All" },
  { id: "508", caste: "Rajput" },
  { id: "117", caste: "Rajput Garhwali" },
  { id: "118", caste: "Rajput Kumaoni" },
  { id: "449", caste: "Hindu: Rajput Negi" },
  { id: "221", caste: "Rajput Rohella Tank" },
  { id: "377", caste: "Ramdasia" },
  { id: "378", caste: "Ramgarhia" },
  { id: "549", caste: "Ramoshi Berad Bedar" },
  { id: "379", caste: "Ravidasia" },
  { id: "380", caste: "Rawat" },
  { id: "119", caste: "Reddy" },
  { id: "639", caste: "Ror" },
  { id: "120", caste: "Sadgope" },
  { id: "381", caste: "Saha" },
  { id: "382", caste: "Sahu" },
  { id: "177", caste: "Saini" },
  { id: "208", caste: "Saliya" },
  { id: "570", caste: "Sathwara" },
  { id: "656", caste: "Savji" },
  { id: "565", caste: "Sawantwadi" },
  { id: "121", caste: "Scheduled Caste" },
  { id: "489", caste: "Hindu: Scheduled Caste- All" },
  { id: "403", caste: "Scheduled Tribe" },
  { id: "490", caste: "Hindu: Scheduled Tribe- All" },
  { id: "209", caste: "Senai Thalaivar" },
  { id: "450", caste: "Senguntha Mudaliyar" },
  { id: "383", caste: "Settibalija" },
  { id: "165", caste: "Shah" },
  { id: "122", caste: "Shimpi" },
  { id: "123", caste: "Sindhi" },
  { id: "492", caste: "Hindu: Sindhi- All" },
  { id: "451", caste: "Hindu: Sindhi Amil" },
  { id: "452", caste: "Hindu: Sindhi Baibhand" },
  { id: "511", caste: "Hindu: Sindhi Bhanusali" },
  { id: "453", caste: "Hindu: Sindhi Bhatia" },
  { id: "536", caste: "Hindu: Sindhi Chhapru" },
  { id: "542", caste: "Hindu: Sindhi Daru" },
  { id: "537", caste: "Hindu: Sindhi Hydrabadi" },
  { id: "454", caste: "Hindu: Sindhi Larai" },
  { id: "538", caste: "Hindu: Sindhi Larkan" },
  { id: "455", caste: "Hindu: Sindhi Larkana" },
  { id: "539", caste: "Hindu: Sindhi Lohana" },
  { id: "456", caste: "Hindu: Sindhi Rohiri" },
  { id: "457", caste: "Hindu: Sindhi Sahiti" },
  { id: "458", caste: "Hindu: Sindhi Sakkhar" },
  { id: "540", caste: "Hindu: Sindhi Sehwani" },
  { id: "459", caste: "Hindu: Sindhi Shikarpuri" },
  { id: "541", caste: "Hindu: Sindhi Thatai" },
  { id: "460", caste: "SKP" },
  { id: "124", caste: "Somvanshi" },
  { id: "241", caste: "Somvanshi Kayastha Prabhu" },
  { id: "125", caste: "Sonar / Sunar" },
  { id: "384", caste: "Hindu: Soni" },
  { id: "461", caste: "Hindu: Sood" },
  { id: "211", caste: "Sourashtra" },
  { id: "126", caste: "Sozhiya Vellalar" },
  { id: "232", caste: "Srisayani" },
  { id: "239", caste: "SSK" },
  { id: "385", caste: "Subarna Banik" },
  { id: "386", caste: "Sudi Suri Sundhi Shaundik" },
  { id: "127", caste: "Sutar" },
  { id: "387", caste: "Swakula sali" },
  { id: "128", caste: "Swarnkar" },
  { id: "388", caste: "Tamboli" },
  { id: "650", caste: "Tammali" },
  { id: "389", caste: "Tanti" },
  { id: "163", caste: "Tantuway" },
  { id: "212", caste: "Telaga" },
  { id: "129", caste: "Teli" },
  { id: "493", caste: "Hindu: Teli- All" },
  { id: "390", caste: "Thakkar" },
  { id: "391", caste: "Hindu: Thakur" },
  { id: "642", caste: "Tharakan" },
  { id: "130", caste: "Thevar Mukkulathor" },
  { id: "392", caste: "Thigala" },
  { id: "131", caste: "Thiyya" },
  { id: "462", caste: "Tili" },
  { id: "463", caste: "Togata" },
  { id: "464", caste: "Tonk Kshatriya" },
  { id: "393", caste: "Tribe" },
  { id: "465", caste: "Turupu Kapu" },
  { id: "394", caste: "Uppara" },
  { id: "577", caste: "Vadar" },
  { id: "395", caste: "Vaddera" },
  { id: "466", caste: "Vaidiki Velanadu" },
  { id: "133", caste: "Vaish" },
  { id: "134", caste: "Hindu: Vaishnav- All" },
  { id: "509", caste: "Vaishnav" },
  { id: "135", caste: "Vaishnav Vanik" },
  { id: "396", caste: "Vaishnava" },
  { id: "136", caste: "Vaishya" },
  { id: "397", caste: "Vaishya Vani" },
  { id: "629", caste: "Vallala" },
  { id: "467", caste: "Valluvar" },
  { id: "137", caste: "Valmiki" },
  { id: "398", caste: "Vania" },
  { id: "399", caste: "Vaniya" },
  { id: "630", caste: "Vanjara" },
  { id: "224", caste: "Vanjari" },
  { id: "236", caste: "Vankar" },
  { id: "213", caste: "Vannar" },
  { id: "214", caste: "Vannia Kula Kshatriyar" },
  { id: "138", caste: "Vanniyar" },
  { id: "624", caste: "Variar" },
  { id: "139", caste: "Varshney" },
  { id: "215", caste: "Veershaiva Veera Saivam" },
  { id: "631", caste: "Velaan" },
  { id: "142", caste: "Velama" },
  { id: "468", caste: "Velan" },
  { id: "141", caste: "Hindu: Vellalar- All" },
  { id: "510", caste: "Vellalar" },
  { id: "469", caste: "Vettuva Gounder" },
  { id: "143", caste: "Vishwakarma" },
  { id: "144", caste: "Vokkaliga" },
  { id: "145", caste: "Vysya" },
  { id: "575", caste: "Wani" },
  { id: "146", caste: "Yadav / Yadava" },
  { id: "632", caste: "Yellapu" },
  { id: "151", caste: "Muslim: Shia" },
  { id: "152", caste: "Muslim: Sunni" },
  { id: "167", caste: "Arora" },
  { id: "472", caste: "Bhatia" },
  { id: "155", caste: "Gursikh" },
  { id: "156", caste: "Jat" },
  { id: "157", caste: "Kamboj" },
  { id: "158", caste: "Kesadhari" },
  { id: "222", caste: "Khashap Rajpoot" },
  { id: "159", caste: "Khatri" },
  { id: "172", caste: "Labana" },
  { id: "248", caste: "Mazhbi" },
  { id: "579", caste: "Nai" },
  { id: "580", caste: "Prajapati" },
  { id: "644", caste: "Rai Sikh" },
  { id: "471", caste: "Rajput" },
  { id: "249", caste: "Ramdasia" },
  { id: "160", caste: "Ramgarhia" },
  { id: "161", caste: "Saini" },
  { id: "563", caste: "Tonk Kshatriya" },
  { id: "174", caste: "Digamber" },
  { id: "175", caste: "Shwetamber" },
];
