import { PartnerPreferrence } from "../ducks/partnerPreferrence/types";

export const partnerPrefEmpty: PartnerPreferrence = {
  actionType: "v",
  userId: 0,
  ageGreaterThan: "0",
  ageLessThan: "0",
  heightGreaterThan: "0",
  heightLessThan: "0",
  country: "[]",
  state: "[]",
  city: "[]",
  education: "[]",
  occupation: "[]",
  annualIncomeGreaterThan: "0",
  maritalStatus: "[]",
  religion: "[]",
  motherTongue: "[]",
  cast: "[]",
  residentialStatus: "[]",
  manglik: "[]",
  diet: "0",
  smoking: "0",
  drinking: "0",
  readyToSettleAbroad: "0",
  challenged: "[]",
  childrenStatus: "[]",
  hiv: "0",
  horoscopeMatch: "0",
  mandatoryFields: "[]",
};
