import { PartnerPreferrence } from "../ducks/partnerPreferrence/types";

export const partnerPrefEmpty: PartnerPreferrence = {
  actionType: "v",
  userId: 0,
  ageGreaterThan: 0,
  ageLessThan: 0,
  heightGreaterThan: "0",
  heightLessThan: "0",
  country: "[0]",
  state: "[0]",
  city: "[0]",
  education: "[0]",
  occupation: "[0]",
  annualIncomeGreaterThan: "0",
  maritalStatus: "[0]",
  religion: "[0]",
  motherTongue: "[0]",
  cast: "[0]",
  residentialStatus: "[0]",
  manglik: "[0]",
  diet: "0",
  smoking: "0",
  drinking: "0",
  readyToSettleAbroad: "0",
  challenged: "[0]",
  childrenStatus: "[0]",
  hiv: "0",
  horoscopeMatch: "0",
  mandatoryFields: "[]",
};
