// import { MotherTongue } from "../types/enums";

export const MotherTongueArr = [
  "Hindi",
  "Hindi_Delhi_Punjabi",
  "Hindi_MP_CG",
  "Hindi_UP_UK",
  "Punjabi",
  "Hindi_Bihar_Jharkhand",
  "Hindi_Rajasthan",
  "Haryanvi",
  "Himachali",
  "Kashmiri",
  "Sindhi",
  "Urdu",
  "Marathi",
  "Gujarati",
  "Kutchi",
  "Konkani",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Tulu",
  "Bengali",
  "Oriya",
  "Assamese",
  "Sikkim_or_Nepali",
  "English",
];

export const MaritalStatusList = [
  "Never Married",
  "Awaiting Divorce",
  "Divorced",
  "Widowed",
  "Annulled",
];

export const ResidentialList = [
  "Citizen",
  "Permanent Resident",
  "Work Permit",
  "Student Visa",
  "Temporary Visa",
];

export const AgeFromYearList = [
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
];
export const AgeToYearList = [
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
];

// export const HeightList =["3","4","5","6","7","8"]
export const HeightList = [
  `3' 0"`,
  `3' 1"`,
  `3' 2"`,
  `3' 3"`,
  `3' 4"`,
  `3' 5"`,
  `3' 6"`,
  `3' 7"`,
  `3' 8"`,
  `3' 9"`,
  `3' 10"`,
  `3' 11"`,
  `3' 12"`,
  `4' 0"`,
  `4' 1"`,
  `4' 2"`,
  `4' 3"`,
  `4' 4"`,
  `4' 5"`,
  `4' 6"`,
  `4' 7"`,
  `4' 8"`,
  `4' 9"`,
  `4' 10"`,
  `4' 11"`,
  `4' 12"`,
  `5' 0"`,
  `5' 1"`,
  `5' 2"`,
  `5' 3"`,
  `5' 4"`,
  `5' 5"`,
  `5' 6"`,
  `5' 7"`,
  `5' 8"`,
  `5' 9"`,
  `5' 10"`,
  `5' 11"`,
  `5' 12"`,
  `6' 0"`,
  `6' 1"`,
  `6' 2"`,
  `6' 3"`,
  `6' 4"`,
  `6' 5"`,
  `6' 6"`,
  `6' 7"`,
  `6' 8"`,
  `6' 9"`,
  `6' 10"`,
  `6' 11"`,
  `6' 12"`,
  `7' 0"`,
  `7' 1"`,
  `7' 2"`,
  `7' 3"`,
  `7' 4"`,
  `7' 5"`,
  `7' 6"`,
  `7' 7"`,
  `7' 8"`,
  `7' 9"`,
  `7' 10"`,
  `7' 11"`,
  `7' 12"`,
  `8' 0"`,
  `8' 1"`,
  `8' 2"`,
  `8' 3"`,
  `8' 4"`,
  `8' 5"`,
  `8' 6"`,
  `8' 7"`,
  `8' 8"`,
  `8' 9"`,
  `8' 10"`,
  `8' 11"`,
  `8' 12"`,
];

export const ReligionList = [
  "Hindu",
  "Muslim",
  "Sikh",
  "Christian",
  "Buddhist",
  "Jain",
  "Parsi",
  "Jewish",
  "Bahai",
  "Other",
];

export const CountryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d' Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  // "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  // "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People' s Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People' s Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  // "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];
export const HeighListInCms = (min: number, max: number) => {
  return Array.from({ length: max - min + 1 }, (_, i) => (i + min).toString());
};

export const ManglikList = ["Manglik", "Non Manglik", "Angshik"];
export const Employed_In = ["Not Working", "Study", "Govt Employed"];

export const HighestEducationList = [
  "Diploma",
  "Bachelor' s",
  "B.Ed",
  "Master' s",
  "M.Ed",
  "MBA",
  "M.Tech",
  "PhD",
  "PG Diploma",
  "Adv. Diploma",
  "Cert. ECE",
  "Cert. SE",
  "Cert. Ed Tech",
  "Cert. Ed Lead",
  "Cert. Curr. Inst.",
  "Cert. Adult Ed",
  "Diploma Ed",
  "TEFL",
  "Diploma Montessori",
  "Adv. Diploma Ed",
  "PG Cert. Ed",
  "M.Phil",
  "PhD Ed",
  "Postdoctoral",
  "Exec. MBA",
];

export const city = [
  {
    name: "Pitampura",
    state: "Delhi",
  },
  {
    name: "Ramesh Nagar",
    state: "Delhi",
  },
  {
    name: "Ookhla",
    state: "Delhi",
  },
];

// export { MotherTongue };

export const OccupationData = [
  "GovernmentPublicSector",
  "CivilServices",
  "Defense",
  "BusinessSelfEmployed",
  "NotWorking",
  "Administration",
  "AdvertisingMediaEntertainment",
  "Agricultural",
  "AirlineAviation",
  "Architecture",
  "ArmedForces",
  "BankingFinance",
  "BPOCustomerService",
  "CorporateManagementProfessionals",
  "Doctor",
  "TeacherEducationTraining",
  "Engineering",
  "Hospitality",
  "LawEnforcement",
  "Legal",
  "MerchantNavy",
  "OtherMedicalHealthcare",
  "ScienceResearch",
  "SoftwareIT",
  "TopManagement",
  "Others",
];

export const SmokeDrinkWith = ["Doesnotmatter", "Yes", "No", "Occasionally"];
