export const GALLERY_GET = "GALLERY_GET";
export const GALLERY_SUCCESS = "GALLERY_SUCCESS";
export const GALLERY_FAILURE = "GALLERY_FAILURE";
export const GALLERY_POST = "GALLERY_POST";
export const GALLERY_POST_SUCCESS = "GALLERY_POST_SUCCESS";
export const GALLERY_POST_FAILURE = "GALLERY_POST_FAILURE";
