export const callingCodes = [
  { countryName: "Afghanistan", callingCode: "+93", code: "AF", flag: "🇦🇫" },
  { countryName: "Albania", callingCode: "+355", code: "AL", flag: "🇦🇱" },
  { countryName: "Algeria", callingCode: "+213", code: "DZ", flag: "🇩🇿" },
  {
    countryName: "AmericanSamoa",
    callingCode: "+1684",
    code: "AS",
    flag: "🇦🇸",
  },
  { countryName: "Andorra", callingCode: "+376", code: "AD", flag: "🇦🇩" },
  { countryName: "Angola", callingCode: "+244", code: "AO", flag: "🇦🇴" },
  { countryName: "Anguilla", callingCode: "+1264", code: "AI", flag: "🇦🇮" },
  { countryName: "Antarctica", callingCode: "+672", code: "AQ", flag: "🇦🇶" },
  {
    countryName: "Antigua and Barbuda",
    callingCode: "+1268",
    code: "AG",
    flag: "🇦🇬",
  },
  { countryName: "Argentina", callingCode: "+54", code: "AR", flag: "🇦🇷" },
  { countryName: "Armenia", callingCode: "+374", code: "AM", flag: "🇦🇲" },
  { countryName: "Aruba", callingCode: "+297", code: "AW", flag: "🇦🇼" },
  {
    countryName: "Australia",
    callingCode: "+61",
    code: "AU",
    preferred: true,
    flag: "🇦🇺",
  },
  { countryName: "Austria", callingCode: "+43", code: "AT", flag: "🇦🇹" },
  { countryName: "Azerbaijan", callingCode: "+994", code: "AZ", flag: "🇦🇿" },
  { countryName: "Bahamas", callingCode: "+1242", code: "BS", flag: "🇧🇸" },
  { countryName: "Bahrain", callingCode: "+973", code: "BH", flag: "🇧🇭" },
  { countryName: "Bangladesh", callingCode: "+880", code: "BD", flag: "🇧🇩" },
  { countryName: "Barbados", callingCode: "+1246", code: "BB", flag: "🇧🇧" },
  { countryName: "Belarus", callingCode: "+375", code: "BY", flag: "🇧🇾" },
  { countryName: "Belgium", callingCode: "+32", code: "BE", flag: "🇧🇪" },
  { countryName: "Belize", callingCode: "+501", code: "BZ", flag: "🇧🇿" },
  { countryName: "Benin", callingCode: "+229", code: "BJ", flag: "🇧🇯" },
  { countryName: "Bermuda", callingCode: "+1441", code: "BM", flag: "🇧🇲" },
  { countryName: "Bhutan", callingCode: "+975", code: "BT", flag: "🇧🇹" },
  {
    countryName: "Bolivia, Plurinational State of",
    callingCode: "+591",
    code: "BO",
    flag: "🇧🇴",
  },
  {
    countryName: "Bosnia and Herzegovina",
    callingCode: "+387",
    code: "BA",
    flag: "🇧🇦",
  },
  { countryName: "Botswana", callingCode: "+267", code: "BW", flag: "🇧🇼" },
  { countryName: "Brazil", callingCode: "+55", code: "BR", flag: "🇧🇷" },
  {
    countryName: "British Indian Ocean Territory",
    callingCode: "+246",
    code: "IO",
    flag: "🇮🇴",
  },
  {
    countryName: "Brunei Darussalam",
    callingCode: "+673",
    code: "BN",
    flag: "🇧🇳",
  },
  { countryName: "Bulgaria", callingCode: "+359", code: "BG", flag: "🇧🇬" },
  { countryName: "Burkina Faso", callingCode: "+226", code: "BF", flag: "🇧🇫" },
  { countryName: "Burundi", callingCode: "+257", code: "BI", flag: "🇧🇮" },
  { countryName: "Cambodia", callingCode: "+855", code: "KH", flag: "🇰🇭" },
  { countryName: "Cameroon", callingCode: "+237", code: "CM", flag: "🇨🇲" },
  { countryName: "Canada", callingCode: "+1", code: "CA", flag: "🇨🇦" },
  { countryName: "Cape Verde", callingCode: "+238", code: "CV", flag: "🇨🇻" },
  {
    countryName: "Cayman Islands",
    callingCode: "+345",
    code: "KY",
    flag: "🇰🇾",
  },
  {
    countryName: "Central African Republic",
    callingCode: "+236",
    code: "CF",
    flag: "🇨🇫",
  },
  { countryName: "Chad", callingCode: "+235", code: "TD", flag: "🇹🇩" },
  { countryName: "Chile", callingCode: "+56", code: "CL", flag: "🇨🇱" },
  { countryName: "China", callingCode: "+86", code: "CN", flag: "🇨🇳" },
  {
    countryName: "Christmas Island",
    callingCode: "+61",
    code: "CX",
    flag: "🇨🇽",
  },
  {
    countryName: "Cocos (Keeling) Islands",
    callingCode: "+61",
    code: "CC",
    flag: "🇨🇨",
  },
  { countryName: "Colombia", callingCode: "+57", code: "CO", flag: "🇨🇴" },
  { countryName: "Comoros", callingCode: "+269", code: "KM", flag: "🇰🇲" },
  { countryName: "Congo", callingCode: "+242", code: "CG", flag: "🇨🇬" },
  {
    countryName: "Congo, The Democratic Republic of the",
    callingCode: "+243",
    code: "CD",
    flag: "🇨🇩",
  },
  { countryName: "Cook Islands", callingCode: "+682", code: "CK", flag: "🇨🇰" },
  { countryName: "Costa Rica", callingCode: "+506", code: "CR", flag: "🇨🇷" },
  { countryName: "Cote d'Ivoire", callingCode: "+225", code: "CI", flag: "🇨🇮" },
  { countryName: "Croatia", callingCode: "+385", code: "HR", flag: "🇭🇷" },
  { countryName: "Cuba", callingCode: "+53", code: "CU", flag: "🇨🇺" },
  { countryName: "Cyprus", callingCode: "+537", code: "CY", flag: "🇨🇾" },
  {
    countryName: "Czech Republic",
    callingCode: "+420",
    code: "CZ",
    flag: "🇨🇿",
  },
  { countryName: "Denmark", callingCode: "+45", code: "DK", flag: "🇩🇰" },
  { countryName: "Djibouti", callingCode: "+253", code: "DJ", flag: "🇩🇯" },
  { countryName: "Dominica", callingCode: "+1767", code: "DM", flag: "🇩🇲" },
  {
    countryName: "Dominican Republic",
    callingCode: "+1849",
    code: "DO",
    flag: "🇩🇴",
  },
  { countryName: "Ecuador", callingCode: "+593", code: "EC", flag: "🇪🇨" },
  { countryName: "Egypt", callingCode: "+20", code: "EG", flag: "🇪🇬" },
  { countryName: "El Salvador", callingCode: "+503", code: "SV", flag: "🇸🇻" },
  {
    countryName: "Equatorial Guinea",
    callingCode: "+240",
    code: "GQ",
    flag: "🇬🇶",
  },
  { countryName: "Eritrea", callingCode: "+291", code: "ER", flag: "🇪🇷" },
  { countryName: "Estonia", callingCode: "+372", code: "EE", flag: "🇪🇪" },
  { countryName: "Ethiopia", callingCode: "+251", code: "ET", flag: "🇪🇹" },
  {
    countryName: "Falkland Islands (Malvinas)",
    callingCode: "+500",
    code: "FK",
    flag: "🇫🇰",
  },
  { countryName: "Faroe Islands", callingCode: "+298", code: "FO", flag: "🇫🇴" },
  { countryName: "Fiji", callingCode: "+679", code: "FJ", flag: "🇫🇯" },
  { countryName: "Finland", callingCode: "+358", code: "FI", flag: "🇫🇮" },
  { countryName: "France", callingCode: "+33", code: "FR", flag: "🇫🇷" },
  { countryName: "French Guiana", callingCode: "+594", code: "GF", flag: "🇬🇫" },
  {
    countryName: "French Polynesia",
    callingCode: "+689",
    code: "PF",
    flag: "🇵🇫",
  },
  { countryName: "Gabon", callingCode: "+241", code: "GA", flag: "🇬🇦" },
  { countryName: "Gambia", callingCode: "+220", code: "GM", flag: "🇬🇲" },
  { countryName: "Georgia", callingCode: "+995", code: "GE", flag: "🇬🇪" },
  { countryName: "Germany", callingCode: "+49", code: "DE", flag: "🇩🇪" },
  { countryName: "Ghana", callingCode: "+233", code: "GH", flag: "🇬🇭" },
  { countryName: "Gibraltar", callingCode: "+350", code: "GI", flag: "🇬🇮" },
  { countryName: "Greece", callingCode: "+30", code: "GR", flag: "🇬🇷" },
  { countryName: "Greenland", callingCode: "+299", code: "GL", flag: "🇬🇱" },
  { countryName: "Grenada", callingCode: "+1473", code: "GD", flag: "🇬🇩" },
  { countryName: "Guadeloupe", callingCode: "+590", code: "GP", flag: "🇬🇵" },
  { countryName: "Guam", callingCode: "+1671", code: "GU", flag: "🇬🇺" },
  { countryName: "Guatemala", callingCode: "+502", code: "GT", flag: "🇬🇹" },
  { countryName: "Guernsey", callingCode: "+44", code: "GG", flag: "🇬🇬" },
  { countryName: "Guinea", callingCode: "+224", code: "GN", flag: "🇬🇳" },
  { countryName: "Guinea-Bissau", callingCode: "+245", code: "GW", flag: "🇬🇼" },
  { countryName: "Guyana", callingCode: "+595", code: "GY", flag: "🇬🇾" },
  { countryName: "Haiti", callingCode: "+509", code: "HT", flag: "🇭🇹" },
  {
    countryName: "Holy See (Vatican City State)",
    callingCode: "+379",
    code: "VA",
    flag: "🇻🇦",
  },
  { countryName: "Honduras", callingCode: "+504", code: "HN", flag: "🇭🇳" },
  { countryName: "Hong Kong", callingCode: "+852", code: "HK", flag: "🇭🇰" },
  { countryName: "Hungary", callingCode: "+36", code: "HU", flag: "🇭🇺" },
  { countryName: "Iceland", callingCode: "+354", code: "IS", flag: "🇮🇸" },
  {
    countryName: "India",
    callingCode: "+91",
    code: "IN",
    preferred: true,
    flag: "🇮🇳",
  },
  { countryName: "Indonesia", callingCode: "+62", code: "ID", flag: "🇮🇩" },
  {
    countryName: "Iran, Islamic Republic of",
    callingCode: "+98",
    code: "IR",
    flag: "🇮🇷",
  },
  { countryName: "Iraq", callingCode: "+964", code: "IQ", flag: "🇮🇶" },
  { countryName: "Ireland", callingCode: "+353", code: "IE", flag: "🇮🇪" },
  { countryName: "Isle of Man", callingCode: "+44", code: "IM", flag: "🇮🇲" },
  { countryName: "Israel", callingCode: "+972", code: "IL", flag: "🇮🇱" },
  { countryName: "Italy", callingCode: "+39", code: "IT", flag: "🇮🇹" },
  { countryName: "Jamaica", callingCode: "+1876", code: "JM", flag: "🇯🇲" },
  { countryName: "Japan", callingCode: "+81", code: "JP", flag: "🇯🇵" },
  { countryName: "Jersey", callingCode: "+44", code: "JE", flag: "🇯🇪" },
  { countryName: "Jordan", callingCode: "+962", code: "JO", flag: "🇯🇴" },
  { countryName: "Kazakhstan", callingCode: "+77", code: "KZ", flag: "🇰🇿" },
  { countryName: "Kenya", callingCode: "+254", code: "KE", flag: "🇰🇪" },
  { countryName: "Kiribati", callingCode: "+686", code: "KI", flag: "🇰🇮" },
  {
    countryName: "Korea, Democratic People's Republic of",
    callingCode: "+850",
    code: "KP",
    flag: "🇰🇵",
  },
  {
    countryName: "Korea, Republic of",
    callingCode: "+82",
    code: "KR",
    flag: "🇰🇷",
  },
  { countryName: "Kuwait", callingCode: "+965", code: "KW", flag: "🇰🇼" },
  { countryName: "Kyrgyzstan", callingCode: "+996", code: "KG", flag: "🇰🇬" },
  {
    countryName: "Lao People's Democratic Republic",
    callingCode: "+856",
    code: "LA",
    flag: "🇱🇦",
  },
  { countryName: "Latvia", callingCode: "+371", code: "LV", flag: "🇱🇻" },
  { countryName: "Lebanon", callingCode: "+961", code: "LB", flag: "🇱🇧" },
  { countryName: "Lesotho", callingCode: "+266", code: "LS", flag: "🇱🇸" },
  { countryName: "Liberia", callingCode: "+231", code: "LR", flag: "🇱🇷" },
  {
    countryName: "Libyan Arab Jamahiriya",
    callingCode: "+218",
    code: "LY",
    flag: "🇱🇾",
  },
  { countryName: "Liechtenstein", callingCode: "+423", code: "LI", flag: "🇱🇮" },
  { countryName: "Lithuania", callingCode: "+370", code: "LT", flag: "🇱🇹" },
  { countryName: "Luxembourg", callingCode: "+352", code: "LU", flag: "🇱🇺" },
  { countryName: "Macao", callingCode: "+853", code: "MO", flag: "🇲🇴" },
  {
    countryName: "Macedonia, The Former Yugoslav Republic of",
    callingCode: "+389",
    code: "MK",
    flag: "🇲🇰",
  },
  { countryName: "Madagascar", callingCode: "+261", code: "MG", flag: "🇲🇬" },
  { countryName: "Malawi", callingCode: "+265", code: "MW", flag: "🇲🇼" },
  { countryName: "Malaysia", callingCode: "+60", code: "MY", flag: "🇲🇾" },
  { countryName: "Maldives", callingCode: "+960", code: "MV", flag: "🇲🇻" },
  { countryName: "Mali", callingCode: "+223", code: "ML", flag: "🇲🇱" },
  { countryName: "Malta", callingCode: "+356", code: "MT", flag: "🇲🇹" },
  {
    countryName: "Marshall Islands",
    callingCode: "+692",
    code: "MH",
    flag: "🇲🇭",
  },
  { countryName: "Martinique", callingCode: "+596", code: "MQ", flag: "🇲🇶" },
  { countryName: "Mauritania", callingCode: "+222", code: "MR", flag: "🇲🇷" },
  { countryName: "Mauritius", callingCode: "+230", code: "MU", flag: "🇲🇺" },
  { countryName: "Mayotte", callingCode: "+262", code: "YT", flag: "🇾🇹" },
  { countryName: "Mexico", callingCode: "+52", code: "MX", flag: "🇲🇽" },
  {
    countryName: "Micronesia, Federated States of",
    callingCode: "+691",
    code: "FM",
    flag: "🇫🇲",
  },
  {
    countryName: "Moldova, Republic of",
    callingCode: "+373",
    code: "MD",
    flag: "🇲🇩",
  },
  { countryName: "Monaco", callingCode: "+377", code: "MC", flag: "🇲🇨" },
  { countryName: "Mongolia", callingCode: "+976", code: "MN", flag: "🇲🇳" },
  { countryName: "Montenegro", callingCode: "+382", code: "ME", flag: "🇲🇪" },
  { countryName: "Montserrat", callingCode: "+1664", code: "MS", flag: "🇲🇸" },
  { countryName: "Morocco", callingCode: "+212", code: "MA", flag: "🇲🇦" },
  { countryName: "Mozambique", callingCode: "+258", code: "MZ", flag: "🇲🇿" },
  { countryName: "Myanmar", callingCode: "+95", code: "MM", flag: "🇲🇲" },
  { countryName: "Namibia", callingCode: "+264", code: "NA", flag: "🇳🇦" },
  { countryName: "Nauru", callingCode: "+674", code: "NR", flag: "🇳🇷" },
  { countryName: "Nepal", callingCode: "+977", code: "NP", flag: "🇳🇵" },
  { countryName: "Netherlands", callingCode: "+31", code: "NL", flag: "🇳🇱" },
  {
    countryName: "Netherlands Antilles",
    callingCode: "+599",
    code: "AN",
    flag: "🇦🇳",
  },
  { countryName: "New Caledonia", callingCode: "+687", code: "NC", flag: "🇳🇨" },
  { countryName: "New Zealand", callingCode: "+64", code: "NZ", flag: "🇳🇿" },
  { countryName: "Nicaragua", callingCode: "+505", code: "NI", flag: "🇳🇮" },
  { countryName: "Niger", callingCode: "+227", code: "NE", flag: "🇳🇪" },
  { countryName: "Nigeria", callingCode: "+234", code: "NG", flag: "🇳🇬" },
  { countryName: "Niue", callingCode: "+683", code: "NU", flag: "🇳🇺" },
  {
    countryName: "Norfolk Island",
    callingCode: "+672",
    code: "NF",
    flag: "🇳🇫",
  },
  {
    countryName: "Northern Mariana Islands",
    callingCode: "+1670",
    code: "MP",
    flag: "🇲🇵",
  },
  { countryName: "Norway", callingCode: "+47", code: "NO", flag: "🇳🇴" },
  { countryName: "Oman", callingCode: "+968", code: "OM", flag: "🇴🇲" },
  { countryName: "Pakistan", callingCode: "+92", code: "PK", flag: "🇵🇰" },
  { countryName: "Palau", callingCode: "+680", code: "PW", flag: "🇵🇼" },
  {
    countryName: "Palestinian Territory, Occupied",
    callingCode: "+970",
    code: "PS",
    flag: "🇵🇸",
  },
  { countryName: "Panama", callingCode: "+507", code: "PA", flag: "🇵🇦" },
  {
    countryName: "Papua New Guinea",
    callingCode: "+675",
    code: "PG",
    flag: "🇵🇬",
  },
  { countryName: "Paraguay", callingCode: "+595", code: "PY", flag: "🇵🇾" },
  { countryName: "Peru", callingCode: "+51", code: "PE", flag: "🇵🇪" },
  { countryName: "Philippines", callingCode: "+63", code: "PH", flag: "🇵🇭" },
  { countryName: "Pitcairn", callingCode: "+872", code: "PN", flag: "🇵🇳" },
  { countryName: "Poland", callingCode: "+48", code: "PL", flag: "🇵🇱" },
  { countryName: "Portugal", callingCode: "+351", code: "PT", flag: "🇵🇹" },
  { countryName: "Puerto Rico", callingCode: "+1939", code: "PR", flag: "🇵🇷" },
  { countryName: "Qatar", callingCode: "+974", code: "QA", flag: "🇶🇦" },
  { countryName: "Romania", callingCode: "+40", code: "RO", flag: "🇷🇴" },
  { countryName: "Russia", callingCode: "+7", code: "RU", flag: "🇷🇺" },
  { countryName: "Rwanda", callingCode: "+250", code: "RW", flag: "🇷🇼" },
  { countryName: "Réunion", callingCode: "+262", code: "RE", flag: "🇷🇪" },
  {
    countryName: "Saint Barthélemy",
    callingCode: "+590",
    code: "BL",
    flag: "🇧🇱",
  },
  {
    countryName: "Saint Helena, Ascension and Tristan Da Cunha",
    callingCode: "+290",
    code: "SH",
    flag: "🇸🇭",
  },
  {
    countryName: "Saint Kitts and Nevis",
    callingCode: "+1869",
    code: "KN",
    flag: "🇰🇳",
  },
  { countryName: "Saint Lucia", callingCode: "+1758", code: "LC", flag: "🇱🇨" },
  { countryName: "Saint Martin", callingCode: "+590", code: "MF", flag: "🇲🇫" },
  {
    countryName: "Saint Pierre and Miquelon",
    callingCode: "+508",
    code: "PM",
    flag: "🇵🇲",
  },
  {
    countryName: "Saint Vincent and the Grenadines",
    callingCode: "+1784",
    code: "VC",
    flag: "🇻🇨",
  },
  { countryName: "Samoa", callingCode: "+685", code: "WS", flag: "🇼🇸" },
  { countryName: "San Marino", callingCode: "+378", code: "SM", flag: "🇸🇲" },
  {
    countryName: "Sao Tome and Principe",
    callingCode: "+239",
    code: "ST",
    flag: "🇸🇹",
  },
  { countryName: "Saudi Arabia", callingCode: "+966", code: "SA", flag: "🇸🇦" },
  { countryName: "Senegal", callingCode: "+221", code: "SN", flag: "🇸🇳" },
  { countryName: "Serbia", callingCode: "+381", code: "RS", flag: "🇷🇸" },
  { countryName: "Seychelles", callingCode: "+248", code: "SC", flag: "🇸🇨" },
  { countryName: "Sierra Leone", callingCode: "+232", code: "SL", flag: "🇸🇱" },
  { countryName: "Singapore", callingCode: "+65", code: "SG", flag: "🇸🇬" },
  { countryName: "Slovakia", callingCode: "+421", code: "SK", flag: "🇸🇰" },
  { countryName: "Slovenia", callingCode: "+386", code: "SI", flag: "🇸🇮" },
  {
    countryName: "Solomon Islands",
    callingCode: "+677",
    code: "SB",
    flag: "🇸🇧",
  },
  { countryName: "Somalia", callingCode: "+252", code: "SO", flag: "🇸🇴" },
  { countryName: "South Africa", callingCode: "+27", code: "ZA", flag: "🇿🇦" },
  {
    countryName: "South Georgia and the South Sandwich Islands",
    callingCode: "+500",
    code: "GS",
    flag: "🇬🇸",
  },
  { countryName: "Spain", callingCode: "+34", code: "ES", flag: "🇪🇸" },
  { countryName: "Sri Lanka", callingCode: "+94", code: "LK", flag: "🇱🇰" },
  { countryName: "Sudan", callingCode: "+249", code: "SD", flag: "🇸🇩" },
  {
    countryName: "SuricountryName",
    callingCode: "+597",
    code: "SR",
    flag: "🇸🇷",
  },
  {
    countryName: "Svalbard and Jan Mayen",
    callingCode: "+47",
    code: "SJ",
    flag: "🇸🇯",
  },
  { countryName: "Swaziland", callingCode: "+268", code: "SZ", flag: "🇸🇿" },
  { countryName: "Sweden", callingCode: "+46", code: "SE", flag: "🇸🇪" },
  { countryName: "Switzerland", callingCode: "+41", code: "CH", flag: "🇨🇭" },
  {
    countryName: "Syrian Arab Republic",
    callingCode: "+963",
    code: "SY",
    flag: "🇸🇾",
  },
  {
    countryName: "Taiwan, Province of China",
    callingCode: "+886",
    code: "TW",
    flag: "🇹🇼",
  },
  { countryName: "Tajikistan", callingCode: "+992", code: "TJ", flag: "🇹🇯" },
  {
    countryName: "Tanzania, United Republic of",
    callingCode: "+255",
    code: "TZ",
    flag: "🇹🇿",
  },
  { countryName: "Thailand", callingCode: "+66", code: "TH", flag: "🇹🇭" },
  { countryName: "Timor-Leste", callingCode: "+670", code: "TL", flag: "🇹🇱" },
  { countryName: "Togo", callingCode: "+228", code: "TG", flag: "🇹🇬" },
  { countryName: "Tokelau", callingCode: "+690", code: "TK", flag: "🇹🇰" },
  { countryName: "Tonga", callingCode: "+676", code: "TO", flag: "🇹🇴" },
  {
    countryName: "Trinidad and Tobago",
    callingCode: "+1868",
    code: "TT",
    flag: "🇹🇹",
  },
  { countryName: "Tunisia", callingCode: "+216", code: "TN", flag: "🇹🇳" },
  { countryName: "Turkey", callingCode: "+90", code: "TR", flag: "🇹🇷" },
  { countryName: "Turkmenistan", callingCode: "+993", code: "TM", flag: "🇹🇲" },
  {
    countryName: "Turks and Caicos Islands",
    callingCode: "+1649",
    code: "TC",
    flag: "🇹🇨",
  },
  { countryName: "Tuvalu", callingCode: "+688", code: "TV", flag: "🇹🇻" },
  { countryName: "Uganda", callingCode: "+256", code: "UG", flag: "🇺🇬" },
  { countryName: "Ukraine", callingCode: "+380", code: "UA", flag: "🇺🇦" },
  {
    countryName: "United Arab Emirates",
    callingCode: "+971",
    code: "AE",
    preferred: true,
    flag: "🇦🇪",
  },
  {
    countryName: "United Kingdom",
    callingCode: "+44",
    code: "GB",
    preferred: true,
    flag: "🇬🇧",
  },
  {
    countryName: "United States",
    callingCode: "+1",
    code: "US",
    preferred: true,
    flag: "🇺🇸",
  },
  { countryName: "Uruguay", callingCode: "+598", code: "UY", flag: "🇺🇾" },
  { countryName: "Uzbekistan", callingCode: "+998", code: "UZ", flag: "🇺🇿" },
  { countryName: "Vanuatu", callingCode: "+678", code: "VU", flag: "🇻🇺" },
  {
    countryName: "Venezuela, Bolivarian Republic of",
    callingCode: "+58",
    code: "VE",
    flag: "🇻🇪",
  },
  { countryName: "Viet Nam", callingCode: "+84", code: "VN", flag: "🇻🇳" },
  {
    countryName: "Virgin Islands, British",
    callingCode: "+1284",
    code: "VG",
    flag: "🇻🇬",
  },
  {
    countryName: "Virgin Islands, U.S.",
    callingCode: "+1340",
    code: "VI",
    flag: "🇻🇮",
  },
  {
    countryName: "Wallis and Futuna",
    callingCode: "+681",
    code: "WF",
    flag: "🇼🇫",
  },
  { countryName: "Yemen", callingCode: "+967", code: "YE", flag: "🇾🇪" },
  { countryName: "Zambia", callingCode: "+260", code: "ZM", flag: "🇿🇲" },
  { countryName: "Zimbabwe", callingCode: "+263", code: "ZW", flag: "🇿🇼" },
  { countryName: "Åland Islands", callingCode: "+358", code: "AX", flag: "🇦🇽" },
];
