export interface ISearchByDataPayload {
  userId?: number;
  ageGreaterThan?: number;
  ageLessThan?: number;
  heightGreaterThan?: number;
  heightLessThan?: number;
  country?: number[];
  state?: number[];
  city?: number[];
  education?: number[];
  occupation?: number[];
  annualIncome?: number | "";
  maritalStatus?: number[];
  religion?: number[];
  motherTongue?: number[];
  caste?: number[];
  residentialStatus?: number[];
  manglik?: number[];
  diet?: number;
  smoking?: number;
  drinking?: number;
  readyToSettleAbroad?: number;
  challenged?: number[];
  childrenStatus?: number[];
  hiv?: number;
  mandatoryFields?: number[];
  maxUserId: number;
  limit: number;
  viceVersaFlag: number;
  excludedUsers: number[];
}
export interface ISearchByDataResponse {
  dob: string;
  row: number;
  city: number;
  country: number;
  state: number;
  caste: number;
  photo: string;
  userid: number;
  fullname: string;
  religion: number;
  height_cm: number;
  shortlist: null | number;
  occupation: number;
  education: number;
  user_RM_ID: string;
  privacy_name: null | string;
  annual_income: number;
  privacy_photo: null | string;
  marital_status: number;
  matching_score: number;
  privacy_contact: null | string;
  user_last_login: null | string;
}
